import 'dart:async';
import 'dart:convert';
import 'dart:io' as io;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';
import '../../location/pages/location_picker_page.dart';
import '../../../data/models/listing_model.dart';
import '../../../data/providers/app_auth_provider.dart';
import '../../../data/services/backend_service.dart';
import '../../../shared/styles/app_colors.dart';

class CreateListingPage extends StatefulWidget {
  final Listing? listing;
  const CreateListingPage({super.key, this.listing});

  @override
  State<CreateListingPage> createState() => _CreateListingPageState();
}

class _CreateListingPageState extends State<CreateListingPage> {
  final _formKey = GlobalKey<FormState>();

  final _foodNameController = TextEditingController();
  final _quantityController = TextEditingController();
  final _priceController = TextEditingController();
  final _locationController = TextEditingController();
  final _descriptionController = TextEditingController();

  FoodType _selectedFoodType = FoodType.prepared_meal;
  String _selectedUnit = 'portions';
  RedistributionMode _redistributionMode = RedistributionMode.free;
  HygieneStatus _hygieneStatus = HygieneStatus.excellent;
  DateTime _preparedAt = DateTime.now();
  BusinessType _businessType = BusinessType.restaurant;
  XFile? _pickedXFile;
  final ImagePicker _picker = ImagePicker();
  String _dietaryType = "vegetarian";

  // Rescue Window state
  bool _rescueWindowEnabled = false;
  TimeOfDay _rescueWindowFrom = const TimeOfDay(hour: 22, minute: 0);
  TimeOfDay _rescueWindowTo = const TimeOfDay(hour: 23, minute: 0);

  final TextEditingController _pincodeController = TextEditingController();
  Map<String, double>? _coordinates;

  final List<String> _units = ['kg', 'portions', 'pieces', 'liters'];

  // 🔥 Live preview state
  String? _autoGeneratedImageUrl;
  Timer? _debounceTimer;

  @override
  void initState() {
    super.initState();
    if (widget.listing != null) {
      final l = widget.listing!;
      _foodNameController.text = l.foodName;
      _quantityController.text = l.totalQuantity.toString();
      _priceController.text = l.price?.toString() ?? "";
      _locationController.text = l.locationAddress;
      _pincodeController.text = l.pincode ?? "";
      _descriptionController.text = l.description;
      _selectedFoodType = l.foodType;
      _selectedUnit = l.quantityUnit;
      _redistributionMode = l.redistributionMode;
      _hygieneStatus = l.hygieneStatus;
      _preparedAt = l.preparedAt;
      if (l.businessType != null) {
        _businessType = l.businessType!;
      }
    }

    _foodNameController.addListener(_onFoodNameChanged);
  }

  void _onFoodNameChanged() {
    if (_debounceTimer?.isActive ?? false) _debounceTimer!.cancel();
    _debounceTimer = Timer(const Duration(milliseconds: 500), () {
      if (mounted && _pickedXFile == null) {
        setState(() {
          _autoGeneratedImageUrl = BackendService.generateFoodImageUrl(
            _foodNameController.text.isEmpty
                ? "food"
                : _foodNameController.text,
          );
        });
      }
    });
  }

  @override
  void dispose() {
    _foodNameController.removeListener(_onFoodNameChanged);
    _foodNameController.dispose();
    _quantityController.dispose();
    _priceController.dispose();
    _locationController.dispose();
    _pincodeController.dispose();
    _descriptionController.dispose();
    _debounceTimer?.cancel();
    super.dispose();
  }

  Future<void> _selectDateTime() async {
    final DateTime? date = await showDatePicker(
      context: context,
      initialDate: _preparedAt,
      firstDate: DateTime.now().subtract(const Duration(days: 7)),
      lastDate: DateTime.now(),
      builder: (context, child) {
        return Transform.scale(scale: 0.9, child: child);
      },
    );
    if (date != null) {
      final TimeOfDay? time = await showTimePicker(
        context: context,
        initialTime: TimeOfDay.fromDateTime(_preparedAt),
        builder: (context, child) {
          return Transform.scale(scale: 0.9, child: child);
        },
      );
      if (time != null) {
        setState(() {
          _preparedAt = DateTime(
            date.year,
            date.month,
            date.day,
            time.hour,
            time.minute,
          );
        });
      }
    }
  }

  Future<void> _pickImage() async {
    showModalBottomSheet(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (context) => SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            ListTile(
              leading: const Icon(Icons.camera_alt_outlined),
              title: const Text("Take a photo"),
              onTap: () async {
                Navigator.pop(context);
                final XFile? image = await _picker.pickImage(
                  source: ImageSource.camera,
                  imageQuality: 70,
                );
                if (image != null) {
                  setState(() => _pickedXFile = image);
                }
              },
            ),
            ListTile(
              leading: const Icon(Icons.photo_library_outlined),
              title: const Text("Choose from gallery"),
              onTap: () async {
                Navigator.pop(context);
                final XFile? image = await _picker.pickImage(
                  source: ImageSource.gallery,
                  imageQuality: 70,
                );
                if (image != null) {
                  setState(() => _pickedXFile = image);
                }
              },
            ),
          ],
        ),
      ),
    );
  }

  /// Converts a TimeOfDay to a full DateTime on "today's" date.
  DateTime _timeOfDayToDateTime(TimeOfDay t) {
    final now = DateTime.now();
    return DateTime(now.year, now.month, now.day, t.hour, t.minute);
  }

  /// Calculates the actual start/end for the rescue window,
  /// handling midnight crossings and date shifting as a cohesive window.
  (DateTime, DateTime) _getRescueWindow() {
    final now = DateTime.now();
    DateTime from = _timeOfDayToDateTime(_rescueWindowFrom);
    DateTime to = _timeOfDayToDateTime(_rescueWindowTo);

    // Handle midnight crossing: if to <= from, 'to' must be tomorrow
    if (!to.isAfter(from)) {
      to = to.add(const Duration(days: 1));
    }

    // Shift entire window to tomorrow only if the window has fully passed today
    // (with a small 5-min grace period for currently opening windows)
    if (now.isAfter(to.add(const Duration(minutes: 5)))) {
      from = from.add(const Duration(days: 1));
      to = to.add(const Duration(days: 1));
    }

    return (from, to);
  }

  Future<void> _pickRescueTime({required bool isFrom}) async {
    final initial = isFrom ? _rescueWindowFrom : _rescueWindowTo;
    final picked = await showTimePicker(
      context: context,
      initialTime: initial,
      builder: (ctx, child) => Transform.scale(scale: 0.9, child: child),
    );
    if (picked == null) return;
    setState(() {
      if (isFrom) {
        _rescueWindowFrom = picked;
        // Auto-push 'to' to at least 30 min after 'from'
        final fromDt = _timeOfDayToDateTime(picked);
        final toDt = _timeOfDayToDateTime(_rescueWindowTo);
        if (!toDt.isAfter(fromDt.add(const Duration(minutes: 5)))) {
          _rescueWindowTo = TimeOfDay.fromDateTime(
            fromDt.add(const Duration(minutes: 30)),
          );
        }
      } else {
        _rescueWindowTo = picked;
      }
    });
  }

  Future<void> _submitForm() async {
    if (_formKey.currentState!.validate()) {
      // 1. Validate that a location has been pinned
      if (_coordinates == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text("Please pin your exact pickup location on the map."),
            backgroundColor: Colors.orange,
            behavior: SnackBarBehavior.floating,
          ),
        );
        return;
      }

      // 2. Rescue window validation
      if (_rescueWindowEnabled) {
        final window = _getRescueWindow();
        final fromDt = window.$1;
        final toDt = window.$2;

        if (!toDt.isAfter(fromDt)) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text(
                'Rescue Window closing time must be after opening time.',
              ),
              backgroundColor: Colors.orange,
            ),
          );
          return;
        }

        if (toDt.difference(fromDt).inHours >= 4) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Rescue Window cannot exceed 4 hours.'),
              backgroundColor: Colors.orange,
            ),
          );
          return;
        }

        final safetyThreshold = Listing.calculateExpiryTime(
          _selectedFoodType,
          _preparedAt,
        );
        if (toDt.isAfter(safetyThreshold)) {
          final fmt = DateFormat('hh:mm a').format(safetyThreshold);
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(
                'Food expires at $fmt for this type. Rescue window must close before then.',
              ),
              backgroundColor: Colors.red,
            ),
          );
          return;
        }
      }

      try {
        // 1. Compute pickup window
        DateTime pickupFrom;
        DateTime pickupTo;

        if (_rescueWindowEnabled) {
          final window = _getRescueWindow();
          pickupFrom = window.$1;
          pickupTo = window.$2;
        } else {
          pickupFrom = _preparedAt;
          pickupTo = Listing.calculateExpiryTime(
            _selectedFoodType,
            _preparedAt,
          );
        }

        // 2. Get real user IDs
        final authProvider = Provider.of<AppAuthProvider>(
          context,
          listen: false,
        );
        final firebaseUser = authProvider.currentUser;
        if (firebaseUser == null) throw Exception("User not logged in");

        final profileData = await BackendService.getUserProfile(
          firebaseUser.uid,
        );
        final realSellerId = profileData['user']['_id'];
        final realSellerProfileId = profileData['profile']['_id'];

        final listingMap = {
          "sellerId": realSellerId,
          "sellerProfileId": realSellerProfileId,
          "foodName": _foodNameController.text,
          "foodType": _selectedFoodType.name,
          "dietaryType": _dietaryType,
          "category": "cooked",
          "quantityText": "${_quantityController.text} ${_selectedUnit}",
          "totalQuantity": double.parse(_quantityController.text),
          "description": _descriptionController.text,
          "pricing": {
            "discountedPrice":
                _redistributionMode == RedistributionMode.discounted
                ? double.tryParse(_priceController.text) ?? 0
                : 0,
            "isFree": _redistributionMode == RedistributionMode.free,
          },
          "pickupWindow": {
            "from": pickupFrom.toIso8601String(),
            "to": pickupTo.toIso8601String(),
          },
          "pickupAddressText": _locationController.text,
          "pincode": _pincodeController.text,
          "pickupGeo": {
            "type": "Point",
            "coordinates": _coordinates != null
                ? [_coordinates!['longitude'], _coordinates!['latitude']]
                : [77.5946, 12.9716],
          },
        };

        debugPrint('--- SUBMIT FORM ---');
        debugPrint('Rescue Window: $_rescueWindowEnabled');
        debugPrint('Pickup Window from=$pickupFrom  to=$pickupTo');
        debugPrint('Initial listingMap: ${jsonEncode(listingMap)}');
        debugPrint(
          '_pickedXFile status: ${_pickedXFile != null ? "HAS IMAGE" : "NO IMAGE"}',
        );

        // 3. Upload image if picked
        if (_pickedXFile != null) {
          debugPrint('Uploading image: ${_pickedXFile!.name}...');
          try {
            final bytes = await _pickedXFile!.readAsBytes();
            final imageUrl = await BackendService.uploadImage(
              bytes,
              _pickedXFile!.name,
            );
            debugPrint('Upload success! URL: $imageUrl');
            listingMap["images"] = [imageUrl];
          } catch (e) {
            debugPrint('!!! IMAGE UPLOAD FAILED: $e');
            rethrow;
          }
        } else if (widget.listing != null &&
            widget.listing!.imageUrl.isNotEmpty) {
          debugPrint('Keeping existing image: ${widget.listing!.imageUrl}');
          listingMap["images"] = [widget.listing!.imageUrl];
        }

        debugPrint('Final listingMap being sent: ${jsonEncode(listingMap)}');

        if (widget.listing != null) {
          await BackendService.updateListing(widget.listing!.id, listingMap);
        } else {
          await BackendService.createListing(listingMap);
        }

        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              widget.listing != null
                  ? 'Listing updated successfully!'
                  : 'Listing created successfully!',
            ),
          ),
        );
        Navigator.pop(context);
      } catch (e) {
        debugPrint('Error creating listing: $e');
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: Text(
          widget.listing != null ? "Edit Listing" : "Create Listing",
          style: GoogleFonts.lora(fontWeight: FontWeight.bold, fontSize: 18),
        ),
        backgroundColor: Colors.white,
        elevation: 0,
        foregroundColor: AppColors.textDark,
      ),
      body: Center(
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 800),
          child: SingleChildScrollView(
            child: Padding(
              padding: const EdgeInsets.all(16.0),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _buildSectionTitle("Food Image"),
                    const SizedBox(height: 12),
                    _buildImagePicker(),
                    const SizedBox(height: 24),
                    _buildSectionTitle("Business Information"),
                    const SizedBox(height: 16),
                    _buildDropdown<BusinessType>(
                      label: "Type of Business",
                      value: _businessType,
                      items: BusinessType.values,
                      onChanged: (v) => setState(() => _businessType = v!),
                      itemToString: (e) => _getBusinessTypeLabel(e),
                    ),
                    const SizedBox(height: 24),
                    _buildSectionTitle("Basic Information"),
                    const SizedBox(height: 16),
                    _buildTextField(
                      controller: _foodNameController,
                      label: "Food Name",
                      hint: "e.g. Mixed Veg Curry",
                      validator: (v) => v?.isEmpty ?? true ? "Required" : null,
                    ),
                    const SizedBox(height: 16),
                    _buildCategorySelection(),
                    const SizedBox(height: 16),
                    Row(
                      children: [
                        Expanded(
                          flex: 2,
                          child: _buildTextField(
                            controller: _quantityController,
                            label: "Quantity",
                            hint: "0.0",
                            keyboardType: TextInputType.number,
                            validator: (v) =>
                                v?.isEmpty ?? true ? "Required" : null,
                          ),
                        ),
                        const SizedBox(width: 16),
                        Expanded(
                          flex: 1,
                          child: _buildDropdown<String>(
                            label: "Unit",
                            value: _selectedUnit,
                            items: _units,
                            onChanged: (v) =>
                                setState(() => _selectedUnit = v!),
                            itemToString: (e) => e,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 24),
                    _buildSectionTitle("Redistribution Details"),
                    const SizedBox(height: 12),
                    Row(
                      children: [
                        _buildModeRadio(RedistributionMode.free, "Free"),
                        const SizedBox(width: 24),
                        _buildModeRadio(
                          RedistributionMode.discounted,
                          "Discounted",
                        ),
                      ],
                    ),
                    if (_redistributionMode ==
                        RedistributionMode.discounted) ...[
                      const SizedBox(height: 16),
                      _buildTextField(
                        controller: _priceController,
                        label: "Price (₹)",
                        hint: "0.00",
                        keyboardType: TextInputType.number,
                        validator: (v) =>
                            _redistributionMode ==
                                    RedistributionMode.discounted &&
                                (v?.isEmpty ?? true)
                            ? "Required"
                            : null,
                      ),
                    ],
                    const SizedBox(height: 24),
                    _buildDateTimePicker(),
                    const SizedBox(height: 16),
                    _buildRescueWindowSection(),
                    const SizedBox(height: 16),
                    _buildDropdown<HygieneStatus>(
                      label: "Hygiene Status",
                      value: _hygieneStatus,
                      items: HygieneStatus.values,
                      onChanged: (v) => setState(() => _hygieneStatus = v!),
                      itemToString: (e) =>
                          e.name.substring(0, 1).toUpperCase() +
                          e.name.substring(1),
                    ),
                    const SizedBox(height: 24),
                    _buildTextField(
                      controller: _descriptionController,
                      label: "Description",
                      hint:
                          "e.g. Ingredients, allergens, or special instructions",
                      maxLines: 3,
                    ),
                    const SizedBox(height: 20),
                    _buildSectionTitle("Food Diet"),
                    const SizedBox(height: 12),
                    _buildDietarySelector(),

                    const SizedBox(height: 20),
                    _buildMapPicker(),
                    const SizedBox(height: 32),
                    SizedBox(
                      width: double.infinity,
                      height: 50,
                      child: ElevatedButton(
                        onPressed: _submitForm,
                        style: ElevatedButton.styleFrom(
                          backgroundColor: AppColors.primary,
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                          elevation: 0,
                        ),
                        child: Text(
                          widget.listing != null
                              ? "Update Listing"
                              : "Create Listing",
                          style: const TextStyle(
                            fontSize: 14,
                            fontWeight: FontWeight.bold,
                            color: Colors.white,
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(height: 24),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildDietarySelector() {
    final diets = [
      {
        "label": "Veg",
        "value": "vegetarian",
        "icon": Icons.eco_outlined,
        "color": Colors.green,
      },
      {
        "label": "Non-Veg",
        "value": "non_veg",
        "icon": Icons.kebab_dining_outlined,
        "color": Colors.red,
      },
      {
        "label": "Vegan",
        "value": "vegan",
        "icon": Icons.grass_outlined,
        "color": Colors.teal,
      },
      {
        "label": "Jain",
        "icon": Icons.spa_outlined,
        "value": "jain",
        "color": Colors.orange,
      },
    ];

    return Wrap(
      spacing: 12,
      children: diets.map((diet) {
        final isSelected = _dietaryType == diet['value'];
        return ChoiceChip(
          label: Text(diet['label'] as String),
          selected: isSelected,
          onSelected: (selected) {
            if (selected)
              setState(() => _dietaryType = diet['value'] as String);
          },
          avatar: Icon(
            diet['icon'] as IconData,
            size: 16,
            color: isSelected ? Colors.white : (diet['color'] as Color),
          ),
          selectedColor: diet['color'] as Color,
          backgroundColor: Colors.white,
          labelStyle: TextStyle(
            color: isSelected ? Colors.white : AppColors.textDark,
            fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(20),
            side: BorderSide(
              color: isSelected
                  ? (diet['color'] as Color)
                  : AppColors.textLight.withOpacity(0.2),
            ),
          ),
        );
      }).toList(),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Text(
      title,
      style: GoogleFonts.lora(
        fontSize: 16,
        fontWeight: FontWeight.bold,
        color: AppColors.textDark,
      ),
    );
  }

  Widget _buildTextField({
    required TextEditingController controller,
    required String label,
    required String hint,
    TextInputType keyboardType = TextInputType.text,
    int maxLines = 1,
    String? Function(String?)? validator,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: TextStyle(
            fontSize: 13,
            fontWeight: FontWeight.w600,
            color: AppColors.textDark.withOpacity(0.7),
          ),
        ),
        const SizedBox(height: 6),
        TextFormField(
          controller: controller,
          keyboardType: keyboardType,
          maxLines: maxLines,
          validator: validator,
          decoration: InputDecoration(
            hintText: hint,
            hintStyle: TextStyle(color: AppColors.textLight.withOpacity(0.4)),
            filled: true,
            fillColor: Colors.white,
            contentPadding: const EdgeInsets.symmetric(
              horizontal: 16,
              vertical: 12,
            ),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              borderSide: BorderSide(
                color: AppColors.textLight.withOpacity(0.1),
              ),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              borderSide: BorderSide(
                color: AppColors.textLight.withOpacity(0.1),
              ),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              borderSide: const BorderSide(
                color: AppColors.primary,
                width: 1.5,
              ),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildDropdown<T>({
    required String label,
    required T value,
    required List<T> items,
    required void Function(T?) onChanged,
    required String Function(T) itemToString,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: TextStyle(
            fontSize: 13,
            fontWeight: FontWeight.w600,
            color: AppColors.textDark.withOpacity(0.7),
          ),
        ),
        const SizedBox(height: 6),
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 16),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(10),
            border: Border.all(color: AppColors.textLight.withOpacity(0.1)),
          ),
          child: DropdownButtonHideUnderline(
            child: DropdownButton<T>(
              value: value,
              isExpanded: true,
              onChanged: onChanged,
              items: items.map((T item) {
                return DropdownMenuItem<T>(
                  value: item,
                  child: Text(itemToString(item)),
                );
              }).toList(),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildModeRadio(RedistributionMode mode, String label) {
    bool isSelected = _redistributionMode == mode;
    return GestureDetector(
      onTap: () => setState(() => _redistributionMode = mode),
      child: Row(
        children: [
          Container(
            width: 20,
            height: 20,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              border: Border.all(
                color: isSelected
                    ? AppColors.primary
                    : AppColors.textLight.withOpacity(0.3),
                width: 2,
              ),
            ),
            child: isSelected
                ? Center(
                    child: Container(
                      width: 10,
                      height: 10,
                      decoration: const BoxDecoration(
                        color: AppColors.primary,
                        shape: BoxShape.circle,
                      ),
                    ),
                  )
                : null,
          ),
          const SizedBox(width: 8),
          Text(
            label,
            style: TextStyle(
              fontSize: 14,
              fontWeight: isSelected ? FontWeight.bold : FontWeight.w500,
              color: isSelected ? AppColors.textDark : AppColors.textLight,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildDateTimePicker() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          "Prepared At",
          style: TextStyle(
            fontSize: 13,
            fontWeight: FontWeight.w600,
            color: AppColors.textLight.withOpacity(0.8),
          ),
        ),
        const SizedBox(height: 6),
        InkWell(
          onTap: _selectDateTime,
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: AppColors.textLight.withOpacity(0.1)),
            ),
            child: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                const Icon(
                  Icons.calendar_today_outlined,
                  size: 16,
                  color: AppColors.primary,
                ),
                const SizedBox(width: 10),
                Text(
                  DateFormat('MMM dd, hh:mm a').format(_preparedAt),
                  style: const TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildRescueWindowSection() {
    final amber = const Color(0xFFF59E0B);
    final amberLight = const Color(0xFFFEF3C7);

    String _fmtTime(TimeOfDay t) {
      final h = t.hourOfPeriod == 0 ? 12 : t.hourOfPeriod;
      final m = t.minute.toString().padLeft(2, '0');
      final period = t.period == DayPeriod.am ? 'AM' : 'PM';
      return '$h:$m $period';
    }

    return AnimatedContainer(
      duration: const Duration(milliseconds: 300),
      curve: Curves.easeInOut,
      decoration: BoxDecoration(
        color: _rescueWindowEnabled ? amberLight : Colors.white,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(
          color: _rescueWindowEnabled
              ? amber.withOpacity(0.6)
              : AppColors.textLight.withOpacity(0.1),
          width: _rescueWindowEnabled ? 1.5 : 1,
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Toggle header
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 12, 12, 12),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: _rescueWindowEnabled
                        ? amber.withOpacity(0.15)
                        : AppColors.primary.withOpacity(0.08),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Icon(
                    Icons.schedule_rounded,
                    size: 18,
                    color: _rescueWindowEnabled ? amber : AppColors.primary,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        "Schedule Rescue Window",
                        style: TextStyle(
                          fontSize: 13,
                          fontWeight: FontWeight.w700,
                          color: _rescueWindowEnabled
                              ? const Color(0xFF92400E)
                              : AppColors.textDark,
                        ),
                      ),
                      const SizedBox(height: 2),
                      Text(
                        "Allow pickup only during your closing time",
                        style: TextStyle(
                          fontSize: 11,
                          color: _rescueWindowEnabled
                              ? const Color(0xFFB45309)
                              : AppColors.textLight,
                        ),
                      ),
                    ],
                  ),
                ),
                Switch(
                  value: _rescueWindowEnabled,
                  onChanged: (v) => setState(() => _rescueWindowEnabled = v),
                  activeColor: amber,
                  activeTrackColor: amber.withOpacity(0.3),
                ),
              ],
            ),
          ),

          // Time pickers (visible when enabled)
          if (_rescueWindowEnabled) ...[
            Divider(height: 1, color: amber.withOpacity(0.25)),
            Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    "📍 Buyers can order only during this window",
                    style: TextStyle(
                      fontSize: 11,
                      color: const Color(0xFFB45309),
                      fontStyle: FontStyle.italic,
                    ),
                  ),
                  const SizedBox(height: 14),
                  Row(
                    children: [
                      Expanded(
                        child: _buildTimeChip(
                          label: "Opens At",
                          timeStr: _fmtTime(_rescueWindowFrom),
                          icon: Icons.login_rounded,
                          color: amber,
                          onTap: () => _pickRescueTime(isFrom: true),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: _buildTimeChip(
                          label: "Closes At",
                          timeStr: _fmtTime(_rescueWindowTo),
                          icon: Icons.logout_rounded,
                          color: const Color(0xFFEF4444),
                          onTap: () => _pickRescueTime(isFrom: false),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 12),
                  // Live safety hint
                  Builder(
                    builder: (_) {
                      final safetyDt = Listing.calculateExpiryTime(
                        _selectedFoodType,
                        _preparedAt,
                      );
                      final window = _getRescueWindow();
                      final toDt = window.$2;
                      final isSafe = !toDt.isAfter(safetyDt);
                      final safeStr = DateFormat('hh:mm a').format(safetyDt);
                      return Row(
                        children: [
                          Icon(
                            isSafe
                                ? Icons.check_circle_outline
                                : Icons.warning_amber_rounded,
                            size: 13,
                            color: isSafe ? Colors.green : Colors.red,
                          ),
                          const SizedBox(width: 6),
                          Expanded(
                            child: Text(
                              isSafe
                                  ? 'Safe ✓  Food stays fresh until $safeStr'
                                  : '⚠ Window exceeds safety limit ($safeStr for ${_selectedFoodType.name.replaceAll("_", " ")})',
                              style: TextStyle(
                                fontSize: 10,
                                color: isSafe
                                    ? Colors.green.shade700
                                    : Colors.red,
                                fontWeight: FontWeight.w500,
                              ),
                            ),
                          ),
                        ],
                      );
                    },
                  ),
                ],
              ),
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildTimeChip({
    required String label,
    required String timeStr,
    required IconData icon,
    required Color color,
    required VoidCallback onTap,
  }) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(10),
          border: Border.all(color: color.withOpacity(0.35)),
          boxShadow: [
            BoxShadow(
              color: color.withOpacity(0.08),
              blurRadius: 6,
              offset: const Offset(0, 2),
            ),
          ],
        ),
        child: Row(
          children: [
            Icon(icon, size: 16, color: color),
            const SizedBox(width: 8),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    label,
                    style: TextStyle(
                      fontSize: 10,
                      fontWeight: FontWeight.w600,
                      color: color,
                    ),
                  ),
                  const SizedBox(height: 2),
                  Text(
                    timeStr,
                    style: const TextStyle(
                      fontSize: 13,
                      fontWeight: FontWeight.bold,
                      color: Color(0xFF1F2937),
                    ),
                  ),
                ],
              ),
            ),
            Icon(Icons.edit_outlined, size: 13, color: color.withOpacity(0.6)),
          ],
        ),
      ),
    );
  }

  Widget _buildImagePicker() {
    return GestureDetector(
      onTap: _pickImage,
      child: Container(
        height: 180,
        width: double.infinity,
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(16),
          border: Border.all(color: AppColors.textLight.withOpacity(0.1)),
          image: _pickedXFile != null
              ? DecorationImage(
                  image: kIsWeb
                      ? NetworkImage(_pickedXFile!.path) as ImageProvider
                      : FileImage(io.File(_pickedXFile!.path)),
                  fit: BoxFit.cover,
                )
              : null,
        ),
        child: (_pickedXFile == null)
            ? Stack(
                fit: StackFit.expand,
                children: [
                  // Placeholder Background (Auto-generated or default icon)
                  if (_autoGeneratedImageUrl != null)
                    ClipRRect(
                      borderRadius: BorderRadius.circular(16),
                      child: Image.network(
                        _autoGeneratedImageUrl!,
                        fit: BoxFit.cover,
                        loadingBuilder: (context, child, loadingProgress) {
                          if (loadingProgress == null) return child;
                          return Container(
                            color: AppColors.primary.withOpacity(0.05),
                            child: const Center(
                              child: CircularProgressIndicator(strokeWidth: 2),
                            ),
                          );
                        },
                        errorBuilder: (context, error, stackTrace) =>
                            const SizedBox.shrink(),
                      ),
                    ),
                  // Overlay Text & Icon
                  Container(
                    decoration: BoxDecoration(
                      color: _autoGeneratedImageUrl != null
                          ? Colors.black.withOpacity(0.3)
                          : Colors.transparent,
                      borderRadius: BorderRadius.circular(16),
                    ),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(
                          Icons.add_a_photo_outlined,
                          size: 40,
                          color: _autoGeneratedImageUrl != null
                              ? Colors.white
                              : AppColors.primary.withOpacity(0.5),
                        ),
                        const SizedBox(height: 12),
                        Text(
                          "Add food pictures",
                          style: TextStyle(
                            color: _autoGeneratedImageUrl != null
                                ? Colors.white
                                : AppColors.textLight,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        const SizedBox(height: 4),
                        Text(
                          _autoGeneratedImageUrl != null
                              ? "Auto-preview generated from name"
                              : "Capture or upload from gallery",
                          style: TextStyle(
                            color: _autoGeneratedImageUrl != null
                                ? Colors.white.withOpacity(0.8)
                                : AppColors.textLight.withOpacity(0.5),
                            fontSize: 12,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              )
            : Stack(
                children: [
                  Positioned(
                    top: 12,
                    right: 12,
                    child: GestureDetector(
                      onTap: () => setState(() => _pickedXFile = null),
                      child: Container(
                        padding: const EdgeInsets.all(8),
                        decoration: BoxDecoration(
                          color: Colors.black.withOpacity(0.6),
                          shape: BoxShape.circle,
                        ),
                        child: const Icon(
                          Icons.close,
                          color: Colors.white,
                          size: 16,
                        ),
                      ),
                    ),
                  ),
                ],
              ),
      ),
    );
  }

  Widget _buildCategorySelection() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          "Category",
          style: TextStyle(
            fontSize: 13,
            fontWeight: FontWeight.w600,
            color: AppColors.textLight.withOpacity(0.8),
          ),
        ),
        const SizedBox(height: 8),
        SizedBox(
          height: 80,
          child: ListView(
            scrollDirection: Axis.horizontal,
            children: FoodType.values.map((type) {
              bool isSelected = _selectedFoodType == type;
              return GestureDetector(
                onTap: () => setState(() => _selectedFoodType = type),
                child: Container(
                  width: 80,
                  margin: const EdgeInsets.only(right: 12),
                  decoration: BoxDecoration(
                    color: isSelected ? AppColors.primary : Colors.white,
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                      color: isSelected
                          ? AppColors.primary
                          : AppColors.textLight.withOpacity(0.1),
                    ),
                  ),
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Icon(
                        _getCategoryIcon(type),
                        color: isSelected ? Colors.white : AppColors.textDark,
                        size: 20,
                      ),
                      const SizedBox(height: 6),
                      Text(
                        _getCategoryLabel(type),
                        style: TextStyle(
                          fontSize: 10,
                          fontWeight: FontWeight.bold,
                          color: isSelected
                              ? Colors.white
                              : AppColors.textLight,
                        ),
                        textAlign: TextAlign.center,
                      ),
                    ],
                  ),
                ),
              );
            }).toList(),
          ),
        ),
      ],
    );
  }

  IconData _getCategoryIcon(FoodType type) {
    switch (type) {
      case FoodType.prepared_meal:
        return Icons.restaurant_rounded;
      case FoodType.fresh_produce:
        return Icons.eco_rounded;
      case FoodType.packaged_food:
        return Icons.inventory_2_rounded;
      case FoodType.bakery_item:
        return Icons.bakery_dining_rounded;
      case FoodType.dairy_product:
        return Icons.egg_rounded;
    }
  }

  String _getCategoryLabel(FoodType type) {
    switch (type) {
      case FoodType.prepared_meal:
        return "Meal";
      case FoodType.fresh_produce:
        return "Fresh";
      case FoodType.packaged_food:
        return "Packaged";
      case FoodType.bakery_item:
        return "Bakery";
      case FoodType.dairy_product:
        return "Dairy";
    }
  }

  Widget _buildMapPicker() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        _buildSectionTitle("Logistics"),
        const SizedBox(height: 16),
        TextFormField(
          controller: _locationController,
          decoration: InputDecoration(
            hintText: "Enter your full address",
            hintStyle: TextStyle(color: AppColors.textLight.withOpacity(0.4)),
            filled: true,
            fillColor: Colors.white,
            contentPadding: const EdgeInsets.symmetric(
              horizontal: 16,
              vertical: 12,
            ),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              borderSide: BorderSide(
                color: AppColors.textLight.withOpacity(0.1),
              ),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              borderSide: BorderSide(
                color: AppColors.textLight.withOpacity(0.1),
              ),
            ),
          ),
          maxLines: 2,
          validator: (value) =>
              value == null || value.isEmpty ? "Required" : null,
        ),
        const SizedBox(height: 12),
        TextFormField(
          controller: _pincodeController,
          decoration: InputDecoration(
            hintText: "Pincode",
            hintStyle: TextStyle(color: AppColors.textLight.withOpacity(0.4)),
            prefixIcon: const Icon(Icons.pin_drop_outlined, size: 20),
            filled: true,
            fillColor: Colors.white,
            contentPadding: const EdgeInsets.symmetric(
              horizontal: 16,
              vertical: 12,
            ),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              borderSide: BorderSide(
                color: AppColors.textLight.withOpacity(0.1),
              ),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(10),
              borderSide: BorderSide(
                color: AppColors.textLight.withOpacity(0.1),
              ),
            ),
          ),
          keyboardType: TextInputType.number,
          validator: (value) =>
              value == null || value.isEmpty ? "Required" : null,
        ),
        const SizedBox(height: 16),
        InkWell(
          onTap: () async {
            final result = await Navigator.push<LocationResult>(
              context,
              MaterialPageRoute(
                builder: (context) => LocationPickerPage(
                  initialAddress: _locationController.text,
                  initialPincode: _pincodeController.text,
                ),
              ),
            );

            if (result != null) {
              setState(() {
                _locationController.text = result.address;
                _pincodeController.text = result.pincode;
                _coordinates = {
                  'latitude': result.latitude,
                  'longitude': result.longitude,
                };
              });
            }
          },
          child: Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: _coordinates != null
                  ? AppColors.primary.withOpacity(0.05)
                  : Colors.white,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                color: _coordinates != null
                    ? AppColors.primary.withOpacity(0.4)
                    : AppColors.textLight.withOpacity(0.1),
              ),
            ),
            child: Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color:
                        (_coordinates != null
                                ? AppColors.primary
                                : AppColors.primary)
                            .withOpacity(0.1),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Icon(
                    _coordinates != null
                        ? Icons.check_circle_rounded
                        : Icons.location_on_rounded,
                    size: 20,
                    color: AppColors.primary,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        _coordinates != null
                            ? "Location pinned ✓"
                            : "Pin exact location on map *",
                        style: TextStyle(
                          fontSize: 14,
                          fontWeight: FontWeight.w500,
                          color: _coordinates != null
                              ? AppColors.primary
                              : AppColors.textDark,
                        ),
                      ),
                      if (_coordinates != null)
                        Text(
                          "${_coordinates!['latitude']!.toStringAsFixed(4)}, ${_coordinates!['longitude']!.toStringAsFixed(4)}",
                          style: TextStyle(
                            fontSize: 11,
                            color: AppColors.textLight.withOpacity(0.7),
                          ),
                        ),
                    ],
                  ),
                ),
                const Icon(Icons.chevron_right, color: AppColors.textLight),
              ],
            ),
          ),
        ),
      ],
    );
  }

  String _getBusinessTypeLabel(BusinessType type) {
    switch (type) {
      case BusinessType.restaurant:
        return "Restaurant";
      case BusinessType.cafe:
        return "Cafe";
      case BusinessType.cloud_kitchen:
        return "Cloud Kitchen";
      case BusinessType.pet_shop:
        return "Pet Shop";
      case BusinessType.event_management:
        return "Event Management";
      case BusinessType.cafetaria:
        return "Cafetaria";
    }
  }
}
