import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../services/translation_service.dart';
import 'language_provider.dart';
import 'translation_cache.dart';

class AppLocalizations {
  final Locale locale;
  final BuildContext? context; // Added to allow refreshing UI

  AppLocalizations(this.locale, [this.context]);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome': 'Welcome back',
      'join_us': 'Join Us',
      'how_it_works': 'How it works',
      'trust': 'Trust',
      'impact': 'Impact',
      'login': 'Login',
      'register': 'Create New Account',
      'select_language': 'Select your language',
      'continue': 'Continue',
      'seller_dashboard': 'Seller Dashboard',
      'recent_activity': 'Recent Activity',
      'welcome_back_user': 'Welcome back',
      'discover': 'Discover',
      'browse': 'Browse',
      'orders': 'Orders',
      'favourites': 'Favourites',
      'profile': 'Profile',
      'home': 'Home',
      'deliveries': 'Deliveries',
      'verification': 'Verification',
      'ratings': 'Ratings',
      'overview': 'Overview',
      'listings': 'Listings',
      'active_listings': 'Active Listings',
      'pending_orders': 'Pending Orders',
      'avg_rating': 'Avg. Rating',
      'monthly_earnings': 'Monthly Earnings',
      'new_order_received': 'New Order Received',
      'listing_expiring_soon': 'Listing Expiring Soon',
      'payment_confirmed': 'Payment Confirmed',
      'new_feedback': 'New Feedback',
      'all': 'All',
      'free': 'Free',
      'discounted': 'Discounted',
      'meals': 'Meals',
      'bread_pastries': 'Bread & Pastries',
      'groceries': 'Groceries',
      'pet_food': 'Pet Food',
      'vegan': 'Vegan',
      'vegetarian': 'Vegetarian',
      'non_vegetarian': 'Non-Vegetarian',
      'today': 'Today',
      'ends_in': 'Ends in ',
      'my_profile': 'My Profile',
      'personal_info': 'Personal Information',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'address': 'Address',
      'vehicle_type': 'Vehicle Type',
      'bicycle': 'Bicycle',
      'bike': 'Bike',
      'car': 'Car',
      'save_changes': 'Save Changes',
      'security': 'Security',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'change_password': 'Change Password',
      'logout_btn': 'Logout',
      'my_deliveries': 'My Deliveries',
      'new_requests': 'New Requests',
      'accept_delivery': 'Accept Delivery',
      'pickup': 'Pickup',
      'delivery_label': 'Delivery',
      'inactive_msg':
          'You are currently inactive.\nTurn on availability to receive deliveries and view performance.',
      'new_requests_banner': 'You have 2 new delivery requests waiting!',
      'verified_volunteer': 'Verified Volunteer',
      'top_volunteer': 'Top Volunteer',
      'fifty_deliveries': '50 Deliveries',
      'perfect_streak': 'Perfect Streak',
      'menu': 'Menu',
      'welcome_back_to_ahara': 'Welcome back to Ahara',
      'select_your_role': 'Select your role to login or get started.',
      'login_as_buyer': 'Login as Buyer',
      'login_as_seller': 'Login as Seller',
      'login_as_volunteer': 'Login as Volunteer',
      'buyer_subtitle': 'Find meals and help nearby',
      'seller_subtitle': 'Share surplus food surplus',
      'volunteer_subtitle': 'Help transport or verify meals',
      'new_to_ahara': 'New to Ahara?',
      'create_an_account': 'Create an Account',
      'community_driven_food_sharing': 'COMMUNITY-DRIVEN FOOD SHARING',
      'hero_title': 'Small Acts,\nBig Plates.',
      'hero_body':
          'Join a community of food donors and volunteers turning local surplus into neighborhood meals with care and transparency.',
      'give_food': 'Give Food',
      'give_food_desc': 'Share surplus food',
      'volunteer': 'Volunteer',
      'volunteer_desc': 'Transport & verify',
      'find_a_meal': 'Find a meal',
      'find_a_meal_desc': 'Discover local meals',
      'why_trust_us': 'Why Trust Us',
      'our_global_impact': 'Our Global Impact',
      'welcome_back': 'Welcome Back',
      'login_desc':
          'Login to continue your journey with Ahara and help the community.',
      'EMAIL ADDRESS': 'EMAIL ADDRESS',
      'PASSWORD': 'PASSWORD',
      'email_hint': 'name@example.com',
      'password_hint': 'Enter your password',
      'OR': 'OR',
      'sign_in_with_google': 'Log in with Google',
      'sign_in_with_phone': 'Log in with Phone (OTP)',
      'dont_have_account': "Don't have an account?",
      'loading_profile': 'Loading profile...',
      'how_would_you_like_to_join': 'How would you like\nto join us?',
      'select_role_desc':
          'Select your role to get started with the community and help reduce food waste.',
      'already_registered': 'Already registered?',
      'register_as_buyer': 'Register as Buyer',
      'register_as_seller': 'Register as Seller',
      'register_as_volunteer': 'Register as Volunteer',
      'buyer_reg_desc':
          'Find and purchase surplus meals near you at great prices.',
      'seller_reg_desc': 'List your surplus food and help reduce local waste.',
      'volunteer_reg_desc':
          'Lend a hand in distributing food to those who need it.',
      'hello': 'Hello',
      'orders_placed': 'Orders Placed',
      'unable_to_load': 'Unable to load',
      'your_order_journey': 'Your Order Journey',
      'impact_score': 'Impact Score',
      'impact_score_desc': 'Reflects contribution to waste reduction.',
      'dietary_preferences': 'Dietary Preferences',
      'select_all': 'Select All',
      'clear_all': 'Clear All',
      'dietary_prefs_desc': "We'll filter your feed based on these choices.",
      'your_impact': 'Your Impact',
      'orders_cancelled': 'Orders Cancelled',
      'total_spent': 'Total Spent',
      'detecting_location': 'Detecting location...',
      'location_unavailable': 'Location unavailable',
      'no_places_found': 'No places found in this category',
      'discover_near_you': 'Discover Near You',
      'unknown_food': 'Unknown Food',
      'local_seller': 'Local Seller',
      'FREE': 'FREE',
      'opens': 'Opens',
      'ends': 'Ends',
      'locked': 'Locked',
      'expired': 'Expired',
      'soon': 'Soon',
      'favorite_restaurants': 'Favorite Restaurants',
      'no_favorite_restaurants': 'No favorite restaurants yet',
      'follow_favorites_desc':
          'Follow your favorite places to see their items here!',
      'discover_more': 'Discover More',
      'close': 'Close',
      'items': 'Items',
      'no_active_listings': 'No active listings currently',
      'login_with_another_account': 'Login with another account',
      'my_orders': 'My Orders',
      'history': 'History',
      'no_orders_found': 'No orders found',
      'quantity': 'Quantity',
      'track_order': 'Track Order',
      'search_in_this_area': 'Search in this area',
      'searching_in_area': 'Searching in this area...',
      'no_listings_here': 'No listings here yet',
      'try_changing_filters':
          'Try changing your filters or searching another area.',
      'invite_sellers_desc':
          'Invite sellers in this area to encourage community growth!',
      'search_browse_hint': 'Search city, food or category...',
      'filter': 'Filter',
      'results': 'results',
      'rating': 'Rating',
      'offers': 'Offers',
      'free_food_only': 'Free Food Only',
      'apply_filters': 'Apply Filters',
      'blog': 'Blog',
      'legal': 'Legal',
      'account_details': 'Account Details',
      'notifications': 'Notifications',
      'change_language': 'Change Language',
      'claim_now': 'Claim Now',
      'reserve': 'Reserve',
      'availability': 'Availability',
      'your_badges': 'Your Badges',
      'quick_actions': 'Quick Actions',
      'view_orders': 'View Orders',
      'error_unsafe_donation':
          'Safety Warning: Selected pickup window exceeds safe consumption limit for this food type.',
      'voice_mode_on': 'Voice mode activated. How can I help you?',
      'online': 'Online',
      'away': 'Away',
      'your_statistics': 'Your Statistics',
      'last_updated_just_now': 'Last updated: Just now',
      'achievements': 'Achievements',
      'quick_access': 'Quick Access',
      'incoming_requests': 'Incoming Requests',
      'verified': 'Verified',
      'top_star': 'Top Star',
      'social_hero': 'Social Hero',
      'new_requests_nearby': 'New Requests Nearby',
      'tasks_waiting': '{count} tasks are waiting for you',
      'accept': 'Accept',
      'settings': 'Settings',
      'shift_off': 'Shift is Off',
      'failed_to_load_stats': 'Failed to load statistics',
      'retry': 'Retry',
      'logout': 'Logout',
      'review_received': 'Review received',
      'mins_ago': 'mins ago',
      'hours_ago': 'hours ago',
      'yesterday': 'Yesterday',
      'my_listings': 'My Listings',
      'new_listing': 'New Listing',
      'active': 'Active',
      'completed': 'Completed',
      'expired_tab': 'Expired',
      'relist_listing': 'Relist Listing',
      'relist': 'Relist',
      'no_listings_yet': 'No listings yet',
      'no_completed_listings': 'No completed listings',
      'no_expired_listings': 'No expired listings',
      'start_creating_listing_desc':
          'Start by creating your first food listing',
      'expires_in': 'Expires in',
      'expired_ago': 'Expired ago',
      'hygiene_status': 'Hygiene Status',
      'edit': 'Edit',
      'no_new_requests': 'No new requests',
      'no_active_deliveries': 'No active deliveries',
      'no_completed_deliveries': 'No completed deliveries',
      'view_details': 'View Details',
      'cancel': 'Cancel',
      'error': 'Error',
      'placed': 'Placed',
      'awaiting_volunteer': 'Awaiting Volunteer',
      'volunteer_assigned': 'Volunteer Assigned',
      'assigned': 'Assigned',
      'picked_up': 'Picked Up',
      'in_transit': 'In Transit',
      'delivered': 'Delivered',
      'cancelled': 'Cancelled',
      'otp_label': 'OTP',
      'unknown_item': 'Unknown Item',
      'order': 'Order',
      'order_details': 'Order Details',
      'cancel_order': 'Cancel Order',
      'cancel_confirmation_msg':
          'Are you sure you want to cancel this order? This action cannot be undone.',
      'keep_it': 'No, Keep it',
      'yes_cancel': 'Yes, Cancel',
      'order_cancelled_success': 'Order cancelled successfully',
      'failed_to_cancel': 'Failed to cancel',
      'volunteer_delivery': 'Volunteer Delivery',
      'self_pickup': 'Self-Pickup',
      'fulfillment_mode': 'Fulfillment Mode',
      'unknown_donor': 'Unknown Donor',
      'chat': 'Chat',
      'call': 'Call',
      'no_address_provided': 'No address provided',
      'pickup_before': 'Pickup before',
      'handover_otp': 'HANDOVER OTP',
      'otp_share_warning': 'Share only after receiving and checking food.',
      'regenerate_otp': 'Regenerate if expired',
      'finding_volunteer': 'Finding a volunteer hero...',
      'volunteer_hero': 'Volunteer Hero',
      'track_live': 'Track Live',
      'order_summary': 'ORDER SUMMARY',
      'delivery_fee': 'Delivery Fee',
      'platform_fee': 'Platform Fee',
      'total': 'Total',
      'order_timeline': 'ORDER TIMELINE',
      'food_safety_title': 'FOOD SAFETY & QUALITY',
      'food_safety_desc':
          'This item has been inspected for quality and safety by our volunteers.',
      'get_directions': 'Get Directions',
      'amount': 'Amount',
      'date': 'Date',
      'time': 'Time',
      'order_progress': 'Order Progress',
      'buyer_info': 'Buyer Information',
      'delivery_partner': 'Delivery Partner',
      'pickup_instructions': 'Pickup Instructions',
      'secure_handover': 'Secure Handover',
      'verify': 'Verify',
      'invalid_otp_msg': 'Please enter a valid 4-digit OTP',
      'broadcast_sent': 'Broadcast Sent...',
      'seller_info': 'Seller Information',
      'pickup_address': 'Pickup Address',
      'delivery_address': 'Delivery Address',
      'rescue_details': 'Rescue Details',
      'report_emergency': 'Report Emergency',
      'emergency_desc':
          'Are you facing an issue? This will notify the buyer and seller of a potential delay.',
      'report': 'Report',
      'delivery_verified': 'Delivery verified. Order completed!',
      'get_help': 'GET HELP',
      'pickup_from': 'PICKUP FROM',
      'deliver_to': 'DELIVER TO',
      'message': 'Message',
      'cancel_rescue': 'Cancel Rescue',
      'cancel_rescue_msg':
          'Are you sure you want to cancel this rescue? This will return the order to the pool and notify everyone.',
      'rescue_id': 'RESCUE #',
      'items_count': 'ITEMS',
      'order_failed': 'Order Failed',
      'order_cancelled_label': 'Order Cancelled',
      'cancelled_by': 'Cancelled by: ',
      'reason_label': 'Reason',
      'you_buyer': 'You (Buyer)',
      'you_seller': 'You (Seller)',
      'you_volunteer': 'You (Volunteer)',
      'system_label': 'System',
      'system_no_volunteer': 'System (no volunteer available)',
      'km_away': 'km away',
      'notify_once_assigned': "You'll be notified once assigned.",
      'items_text': 'Items',
      'order_verification_title': 'ORDER VERIFICATION',
      'enter_delivery_otp': 'Enter Delivery OTP',
      'nav_to_dropoff': 'Navigate to Dropoff',
      'nav_to_pickup': 'Navigate to Pickup',
      'requested': 'Requested',
      'order_status_updated': 'Order status updated',
      'order_placed_msg': 'Order placed successfully!',
      'volunteer_assigned_msg': 'Volunteer assigned & on the way!',
      'picked_up_msg': 'Food picked up! Arriving soon.',
      'delivered_msg': 'Food delivered. Enjoy!',
      'completed_msg': 'Hope you enjoyed the meal!',
      'cancelled_msg': 'This order was cancelled.',
      'emergency_hint': 'Reason (Accident, Bike issue, etc.)',
      'emergency_reported_msg': 'Emergency reported. Assistance is notified.',
      'rescue_failed': 'Rescue Failed',
      'rescue_cancelled': 'Rescue Cancelled',
      'could_not_launch_nav': 'Could not launch navigation',
      'pickup_code': 'PICKUP CODE',
      'handover_instruction_buyer':
          "Enter Buyer's Handover OTP once they arrive for pickup.",
      'handover_instruction_volunteer':
          "Enter Volunteer's Pickup OTP to record the collection.",
      'contact_support': 'Contact Support',
      'live_tracking': 'Live Tracking',
      'rate_review': 'Rate & Review Experience',
      'report_issue': 'Report an Issue',
      'failed_to_report': 'Failed to report',
      'unknown_buyer': 'Unknown Buyer',
      'unknown_volunteer': 'Unknown Volunteer',
      'no_instructions_provided': 'No specific instructions provided.',
      'trust_score': 'Trust Score',
      'earn_trust': 'Earn Trust',
      'from_backend': 'From backend',
      'not_available': 'Not available',
      'from_customers': 'From customers',
      'business_impact': 'Business Impact',
      'meals_shared': 'Meals Shared',
      'co2_saved': 'CO2 Saved',
      'total_listings': 'Total Listings',
      'manage_account': 'Manage account',
      'business_details': 'Business details',
      'accessibility': 'Accessibility',
      'easy_mode': 'Easy Mode (Simplified)',
      'easy_mode_desc': 'Large icons and simple flow',
      'trust_verification': 'Trust & Verification',
      'get_verified': 'Get Verified',
      'support': 'Support',
      'help_with_orders': 'Help with orders',
      'total_deliveries': 'Total Deliveries',
      'details': 'Details',
      'just_now': 'Just now',
      'reason_changed_mind': 'Changed my mind',
      'reason_accidental': 'Accidental order',
      'reason_too_far': 'Pickup location too far',
      'reason_not_responsive': 'Seller not responsive',
      'reason_other': 'Other (Type below)',
      'cannot_cancel_now': 'Cannot cancel within 30 minutes of pickup',
      'minutes_remaining': 'minutes remaining to cancel',
      'enter_reason_hint': 'Enter cancellation reason...',
    },
    'hi': {
      'welcome': 'वापस स्वागत है',
      'join_us': 'हमसे जुड़ें',
      'how_it_works': 'यह कैसे काम करता है',
      'trust': 'भरोसा',
      'impact': 'प्रभाव',
      'login': 'लॉगिन',
      'register': 'नया खाता बनाएं',
      'select_language': 'अपनी भाषा चुनें',
      'continue': 'जारी रखें',
      'seller_dashboard': 'विक्रेता डैशबोर्ड',
      'recent_activity': 'हाल की गतिविधि',
      'welcome_back_user': 'वापस स्वागत है, ',
      'discover': 'खोजें',
      'browse': 'ब्राउज़ करें',
      'orders': 'ऑर्डर',
      'favourites': 'पसंदीदा',
      'profile': 'प्रोफ़ाइल',
      'home': 'होम',
      'deliveries': 'डिलिवरी',
      'verification': 'सत्यापन',
      'ratings': 'रेटिंग',
      'overview': 'सिंहावलोकन',
      'listings': 'लिस्टिंग',
      'active_listings': 'सक्रिय लिस्टिंग',
      'pending_orders': 'लंबित ऑर्डर',
      'avg_rating': 'औसत रेटिंग',
      'monthly_earnings': 'मासिक कमाई',
      'new_order_received': 'नया ऑर्डर प्राप्त हुआ',
      'listing_expiring_soon': 'लिस्टिंग जल्द ही समाप्त होने वाली है',
      'payment_confirmed': 'भुगतान की पुष्टि हो गई',
      'new_feedback': 'नई प्रतिक्रिया',
      'all': 'सभी',
      'free': 'मुफ्त',
      'discounted': 'छूट',
      'meals': 'भोजन',
      'bread_pastries': 'ब्रेड और पेस्ट्री',
      'groceries': 'किराना',
      'pet_food': 'पालतू भोजन',
      'vegan': 'शाकाहारी (वीगन)',
      'vegetarian': 'शाकाहारी',
      'non_vegetarian': 'मांसाहारी',
      'today': 'आज',
      'ends_in': 'समाप्त होगा ',
      'my_profile': 'मेरी प्रोफ़ाइल',
      'personal_info': 'व्यक्तिगत जानकारी',
      'full_name': 'पूरा नाम',
      'phone_number': 'फोन नंबर',
      'address': 'पता',
      'vehicle_type': 'वाहन का प्रकार',
      'bicycle': 'साइकिल',
      'bike': 'बाइक',
      'car': 'कार',
      'save_changes': 'बदलाव सहेजें',
      'security': 'सुरक्षा',
      'new_password': 'नया पासवर्ड',
      'confirm_new_password': 'नए पासवर्ड की पुष्टि करें',
      'change_password': 'पासवर्ड बदलें',
      'logout_btn': 'लॉगआउट',
      'my_deliveries': 'मेरी डिलीवरी',
      'new_requests': 'नए अनुरोध',
      'accept_delivery': 'डिलीवरी स्वीकार करें',
      'pickup': 'पिकअप',
      'delivery_label': 'डिलीवरी',
      'inactive_msg':
          'आप वर्तमान में निष्क्रिय हैं।\nडिलीवरी प्राप्त करने और प्रदर्शन देखने के लिए उपलब्धता चालू करें।',
      'new_requests_banner': 'आपके पास 2 नए डिलीवरी अनुरोध प्रतीक्षारत हैं!',
      'verified_volunteer': 'सत्यापित स्वयंसेवक',
      'top_volunteer': 'शीर्ष स्वयंसेवक',
      'fifty_deliveries': '50 डिलीवरी',
      'perfect_streak': 'परफेक्ट स्ट्रीक',
      'hello': 'नमस्ते',
      'orders_placed': 'दिए गए ऑर्डर',
      'unable_to_load': 'लोड करने में असमर्थ',
      'your_order_journey': 'आपकी ऑर्डर यात्रा',
      'impact_score': 'प्रभाव स्कोर',
      'impact_score_desc': 'अपशिष्ट कम करने में योगदान दर्शाता है।',
      'dietary_preferences': 'आहार संबंधी प्राथमिकताएं',
      'select_all': 'सभी चुनें',
      'clear_all': 'सभी साफ़ करें',
      'dietary_prefs_desc':
          'हम इन विकल्पों के आधार पर आपकी फीड को फ़िल्टर करेंगे।',
      'your_impact': 'आपका प्रभाव',
      'orders_cancelled': 'रद्द किए गए ऑर्डर',
      'total_spent': 'कुल खर्च',
      'detecting_location': 'स्थान का पता लगाया जा रहा है...',
      'location_unavailable': 'स्थान उपलब्ध नहीं है',
      'no_places_found': 'इस श्रेणी में कोई स्थान नहीं मिला',
      'discover_near_you': 'अपने आस-पास खोजें',
      'unknown_food': 'अज्ञात भोजन',
      'local_seller': 'स्थानीय विक्रेता',
      'FREE': 'मुफ्त',
      'opens': 'खुलता है',
      'ends': 'समाप्त होता है',
      'locked': 'बंद',
      'expired': 'समाप्त',
      'soon': 'जल्द ही',
      'favorite_restaurants': 'पसंदीदा रेस्टोरेंट',
      'no_favorite_restaurants': 'अभी तक कोई पसंदीदा रेस्टोरेंट नहीं',
      'follow_favorites_desc':
          'अपने पसंदीदा स्थानों को यहाँ देखने के लिए उनका अनुसरण करें!',
      'discover_more': 'और खोजें',
      'close': 'बंद करें',
      'items': 'वस्तुएं',
      'no_active_listings': 'वर्तमान में कोई सक्रिय लिस्टिंग नहीं',
      'login_with_another_account': 'दूसरे खाते से लॉगिन करें',
      'my_orders': 'मेरे ऑर्डर',
      'history': 'इतिहास',
      'no_orders_found': 'कोई ऑर्डर नहीं मिला',
      'quantity': 'मात्रा',
      'track_order': 'ऑर्डर ट्रैक करें',
      'search_in_this_area': 'इस क्षेत्र में खोजें',
      'searching_in_area': 'क्षेत्र में खोजा जा रहा है...',
      'no_listings_here': 'यहाँ अभी तक कोई लिस्टिंग नहीं है',
      'try_changing_filters':
          'अपने फ़िल्टर बदलने या किसी अन्य क्षेत्र में खोजने का प्रयास करें।',
      'invite_sellers_desc':
          'सामुदायिक विकास को प्रोत्साहित करने के लिए इस क्षेत्र में विक्रेताओं को आमंत्रित करें!',
      'search_browse_hint': 'शहर, भोजन या श्रेणी खोजें...',
      'filter': 'फ़िल्टर',
      'results': 'परिणाम',
      'rating': 'रेटिंग',
      'offers': 'ऑफ़र',
      'free_food_only': 'केवल मुफ्त भोजन',
      'apply_filters': 'फ़िल्टर लागू करें',
      'blog': 'ब्लॉग',
      'legal': 'कानूनी',
      'account_details': 'खाते का विवरण',
      'notifications': 'सूचनाएं',
      'change_language': 'भाषा बदलें',
      'order_completed': 'ऑर्डर पूरा हुआ',
      'order_cancelled': 'ऑर्डर रद्द हुआ',
      'no_recent_activity': 'कोई हालिया गतिविधि नहीं',
      'just_now': 'अभी-अभी',
      'days_ago': 'दिन पहले',
      'claim_now': 'अभी प्राप्त करें',
      'reserve': 'आरक्षित करें',
      'availability': 'उपलब्धता',
      'your_badges': 'आपके बैज',
      'quick_actions': 'त्वरित कार्य',
      'view_orders': 'ऑर्डर देखें',
      'error_unsafe_donation':
          'सुरक्षा चेतावनी: चयनित पिकアップ विंडो इस प्रकार के भोजन के लिए सुरक्षित उपभोग सीमा से अधिक है।',
      'voice_mode_on': 'वॉयस मोड सक्रिय। मैं आपकी क्या मदद कर सकता हूँ?',
      'online': 'ऑनलाइन',
      'away': 'अनुपलब्ध',
      'your_statistics': 'आपके आंकड़े',
      'last_updated_just_now': 'अभी अपडेट किया गया',
      'achievements': 'उपलब्धियां',
      'quick_access': 'त्वरित पहुंच',
      'incoming_requests': 'आने वाले अनुरोध',
      'verified': 'सत्यापित',
      'top_star': 'शीर्ष सितारा',
      'social_hero': 'सामाजिक नायक',
      'new_requests_nearby': 'पास में नए अनुरोध',
      'tasks_waiting': 'कार्य आपकी प्रतीक्षा कर रहे हैं',
      'accept': 'स्वीकार करें',
      'settings': 'सेटिंग्स',
      'shift_off': 'शिफ्ट बंद है',
      'failed_to_load_stats': 'आंकड़े लोड करने में विफल',
      'retry': 'पुनः प्रयास करें',
      'logout': 'लॉगआउट',
      'review_received': 'समीक्षा प्राप्त हुई',
      'mins_ago': 'मिनट पहले',
      'hours_ago': 'घंटे पहले',
      'yesterday': 'कल',
      'my_listings': 'मेरी लिस्टिंग',
      'new_listing': 'नई लिस्टिंग',
      'active': 'सक्रिय',
      'completed': 'पूरा हुआ',
      'expired_tab': 'समाप्त',
      'relist_listing': 'फिर से सूचीबद्ध करें',
      'no_listings_yet': 'अभी तक कोई लिस्टिंग नहीं',
      'no_completed_listings': 'कोई पूर्ण लिस्टिंग नहीं',
      'no_expired_listings': 'कोई समाप्त लिस्टिंग नहीं',
      'start_creating_listing_desc': 'अपनी पहली भोजन लिस्टिंग बना कर शुरू करें',
      'expires_in': 'में समाप्त होता है',
      'expired_ago': 'पहले समाप्त हो गया',
      'hygiene_status': 'स्वच्छता की स्थिति',
      'edit': 'संपादित करें',
      'no_new_requests': 'कोई नया अनुरोध नहीं',
      'no_active_deliveries': 'कोई सक्रिय डिलीवरी नहीं',
      'no_completed_deliveries': 'कोई पूर्ण डिलीवरी नहीं',
      'view_details': 'विवरण देखें',
      'placed': 'ऑर्डर दिया गया',
      'awaiting_volunteer': 'स्वयंसेवक की प्रतीक्षा है',
      'volunteer_assigned': 'स्वयंसेवक नियुक्त',
      'assigned': 'नियुक्त',
      'picked_up': 'पिकअप किया गया',
      'in_transit': 'रास्ते में है',
      'delivered': 'डिलिवर किया गया',
      'cancelled': 'रद्द किया गया',
      'otp_label': 'ओटीपी',
      'unknown_item': 'अज्ञात वस्तु',
      'order': 'ऑर्डर',
      'order_details': 'ऑर्डर विवरण',
      'cancel_order': 'ऑर्डर रद्द करें',
      'cancel_confirmation_msg':
          'क्या आप वाकई इस ऑर्डर को रद्द करना चाहते हैं? इस क्रिया को पूर्ववत नहीं किया जा सकता।',
      'keep_it': 'नहीं, रखें',
      'yes_cancel': 'हाँ, रद्द करें',
      'order_cancelled_success': 'ऑर्डर सफलतापूर्वक रद्द कर दिया गया',
      'failed_to_cancel': 'रद्द करने में विफल',
      'volunteer_delivery': 'स्वयंसेवक डिलीवरी',
      'self_pickup': 'स्वयं उठाएं (सेल्फ-पिकअप)',
      'fulfillment_mode': 'पूर्ति मोड',
      'unknown_donor': 'अज्ञात दाता',
      'chat': 'चैट',
      'call': 'कॉल',
      'no_address_provided': 'कोई पता प्रदान नहीं किया गया',
      'pickup_before': 'इससे पहले उठाएं',
      'handover_otp': 'हैंडओवर ओटीपी',
      'otp_share_warning': 'भोजन प्राप्त करने और जांचने के बाद ही साझा करें।',
      'regenerate_otp': 'यदि समाप्त हो गया है तो पुन: उत्पन्न करें',
      'finding_volunteer': 'स्वयंसेवक की तलाश है...',
      'volunteer_hero': 'स्वयंसेवक नायक',
      'track_live': 'लाइव ट्रैक करें',
      'order_summary': 'ऑर्डर सारांश',
      'delivery_fee': 'डिलीवरी शुल्क',
      'platform_fee': 'प्लेटफ़ॉर्म शुल्क',
      'total': 'कुल',
      'order_timeline': 'ऑर्डर टाइमलाइन',
      'food_safety_title': 'खाद्य सुरक्षा और गुणवत्ता',
      'food_safety_desc':
          'हमारे स्वयंसेवकों द्वारा इस वस्तु की गुणवत्ता और सुरक्षा की जांच की गई है।',
      'get_directions': 'दिशा-निर्देश प्राप्त करें',
      'amount': 'राशि',
      'date': 'दिनांक',
      'time': 'समय',
      'order_progress': 'ऑर्डर की प्रगति',
      'buyer_info': 'खरीदार की जानकारी',
      'delivery_partner': 'डिलीवरी पार्टनर',
      'pickup_instructions': 'पिकअप निर्देश',
      'secure_handover': 'सुरक्षित हैंडओवर',
      'verify': 'सत्यापित करें',
      'invalid_otp_msg': 'कृपया एक वैध 4-अंकीय ओटीपी दर्ज करें',
      'broadcast_sent': 'प्रसारण भेजा गया...',
      'seller_info': 'विक्रेता की जानकारी',
      'pickup_address': 'पिकअप पता',
      'delivery_address': 'डिलीवरी का पता',
      'rescue_details': 'रेस्क्यू विवरण',
      'report_emergency': 'आपातकाल की रिपोर्ट करें',
      'emergency_desc':
          'क्या आप किसी समस्या का सामना कर रहे हैं? यह खरीदार और विक्रेता को संभावित देरी के बारे में सूचित करेगा।',
      'report': 'रिपोर्ट',
      'delivery_verified': 'डिलीवरी सत्यापित। ऑर्डर पूरा हुआ!',
      'get_help': 'मदद लें',
      'pickup_from': 'यहाँ से उठाएं',
      'deliver_to': 'यहाँ पहुँचाएँ',
      'message': 'संदेश',
      'cancel_rescue': 'रेस्क्यू रद्द करें',
      'cancel_rescue_msg':
          'क्या आप वाकई इस रेस्क्यू को रद्द करना चाहते हैं? यह ऑर्डर को पूल में वापस भेज देगा और सभी को सूचित करेगा।',
      'rescue_id': 'रेस्क्यू #',
      'items_count': 'वस्तुएं',
      'order_failed': 'ऑर्डर विफल',
      'order_cancelled_label': 'ऑर्डर रद्द',
      'cancelled_by': 'इनके द्वारा रद्द: ',
      'reason_label': 'कारण',
      'you_buyer': 'आप (खरीदार)',
      'you_seller': 'आप (विक्रेता)',
      'you_volunteer': 'आप (स्वयंसेवक)',
      'system_label': 'सिस्टम',
      'system_no_volunteer': 'सिस्टम (कोई स्वयंसेवक उपलब्ध नहीं)',
      'km_away': 'किमी दूर',
      'notify_once_assigned': 'नियुक्त होने पर आपको सूचित किया जाएगा।',
      'items_text': 'वस्तुएं',
      'order_verification_title': 'ऑर्डर सत्यापन',
      'enter_delivery_otp': 'डिलीवरी ओटीपी दर्ज करें',
      'nav_to_dropoff': 'ड्रॉपऑफ़ पर नेविगेट करें',
      'nav_to_pickup': 'पिकअप पर नेविगेट करें',
      'requested': 'अनुरोध किया गया',
      'order_status_updated': 'ऑर्डर की स्थिति अपडेट की गई',
      'order_placed_msg': 'ऑर्डर सफलतापूर्वक दिया गया!',
      'volunteer_assigned_msg': 'स्वयंसेवक नियुक्त और रास्ते में है!',
      'picked_up_msg': 'भोजन उठा लिया गया! जल्द आ रहा है।',
      'delivered_msg': 'भोजन वितरित किया गया। आनंद लें!',
      'completed_msg': 'आशा है कि आपने भोजन का आनंद लिया!',
      'cancelled_msg': 'यह ऑर्डर रद्द कर दिया गया था।',
      'emergency_hint': 'कारण (दुर्घटना, बाइक की समस्या, आदि)',
      'emergency_reported_msg':
          'आपातकाल की रिपोर्ट दी गई। सहायता को सूचित कर दिया गया है।',
      'rescue_failed': 'रेस्क्यू विफल',
      'rescue_cancelled': 'रेस्क्यू रद्द',
      'could_not_launch_nav': 'नेविगेशन शुरू नहीं किया जा सका',
      'pickup_code': 'पिकअप कोड',
      'handover_instruction_buyer':
          'खरीदार के आने पर उनका हैंडओवर ओटीपी दर्ज करें।',
      'handover_instruction_volunteer':
          'कलेक्शन रिकॉर्ड करने के लिए स्वयंसेवक का पिकअप ओटीपी दर्ज करें।',
      'contact_support': 'सहायता से संपर्क करें',
      'live_tracking': 'लाइव ट्रैकिंग',
      'rate_review': 'रेटिंग और समीक्षा',
      'report_issue': 'समस्या की रिपोर्ट करें',
      'failed_to_report': 'रिपोर्ट करने में विफल',
      'unknown_buyer': 'अज्ञात खरीदार',
      'unknown_volunteer': 'अज्ञात स्वयंसेवक',
      'no_instructions_provided': 'कोई विशेष निर्देश प्रदान नहीं किया गया।',
      'trust_score': 'ट्रस्ट स्कोर',
      'earn_trust': 'विश्वास अर्जित करें',
      'from_backend': 'बैकएंड से',
      'not_available': 'उपलब्ध नहीं',
      'from_customers': 'ग्राहकों से',
      'business_impact': 'व्यापार प्रभाव',
      'meals_shared': 'भोजन साझा किया',
      'co2_saved': 'CO2 बचाया',
      'total_listings': 'कुल लिस्टिंग',
      'manage_account': 'खाता प्रबंधित करें',
      'business_details': 'व्यापार विवरण',
      'accessibility': 'पहुंच-योग्यता',
      'easy_mode': 'आसान मोड (सरलीकृत)',
      'easy_mode_desc': 'बड़े आइकन और सरल प्रवाह',
      'trust_verification': 'विश्वास और सत्यापन',
      'get_verified': 'सत्यापित हों',
      'support': 'सहायता',
      'help_with_orders': 'ऑर्डर में सहायता',
      'total_deliveries': 'कुल डिलीवरी',
      'details': 'विवरण',
      'reason_changed_mind': 'मन बदल गया',
      'reason_accidental': 'गलती से ऑर्डर हो गया',
      'reason_too_far': 'पिकअप स्थान बहुत दूर है',
      'reason_not_responsive': 'विक्रेता प्रतिक्रिया नहीं दे रहा है',
      'reason_other': 'अन्य (नीचे लिखें)',
      'cannot_cancel_now': 'पिकअप के 30 मिनट के भीतर रद्द नहीं किया जा सकता',
      'minutes_remaining': 'रद्द करने के लिए मिनट बचे हैं',
      'enter_reason_hint': 'रद्द करने का कारण दर्ज करें...',
    },
    'ta': {
      'welcome': 'மீண்டும் வருக',
      'join_us': 'எங்களுடன் இணையுங்கள்',
      'how_it_works': 'இது எப்படி வேலை செய்கிறது',
      'trust': 'நம்பிக்கை',
      'impact': 'தாக்கம்',
      'login': 'உள்நுழைக',
      'register': 'புதிய கணக்கை உருவாக்கு',
      'select_language': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
      'continue': 'தொடரவும்',
      'seller_dashboard': 'விற்பனையாளர் டாஷ்போர்டு',
      'recent_activity': 'சமீபத்திய செயல்பாடு',
      'welcome_back_user': 'மீண்டும் வருக, ',
      'discover': 'கண்டுபிடி',
      'browse': 'உலவு',
      'orders': 'ஆர்டர்கள்',
      'favourites': 'விருப்பமானவை',
      'profile': 'சுயவிவரம்',
      'home': 'முகப்பு',
      'deliveries': 'டெலிவரிகள்',
      'verification': 'சரிபார்ப்பு',
      'ratings': 'மதிப்பீடுகள்',
      'overview': 'கண்ணோட்டம்',
      'listings': 'பட்டியல்கள்',
      'active_listings': 'செயலில் உள்ள பட்டியல்கள்',
      'pending_orders': 'நிலுவையில் உள்ள ஆர்டர்கள்',
      'avg_rating': 'சராசரி மதிப்பீடு',
      'monthly_earnings': 'மாதாந்திர வருமானம்',
      'new_order_received': 'புதிய ஆர்டர் பெறப்பட்டது',
      'listing_expiring_soon': 'பட்டியல் விரைவில் காலாவதியாகிறது',
      'payment_confirmed': 'பணம் செலுத்துதல் உறுதி செய்யப்பட்டது',
      'new_feedback': 'புதிய கருத்து',
      'all': 'அனைத்தும்',
      'free': 'இலவசம்',
      'discounted': 'தள்ளுபடி',
      'meals': 'உணவுகள்',
      'bread_pastries': 'ரொட்டி மற்றும் பேஸ்ட்ரிகள்',
      'groceries': 'மளிகைப் பொருட்கள்',
      'pet_food': 'செல்லப்பிராணி உணவு',
      'vegan': 'சைவம் (வீகன்)',
      'vegetarian': 'சைவம்',
      'non_vegetarian': 'அசைவம்',
      'today': 'இன்று',
      'ends_in': 'முடிவடைகிறது ',
      'my_profile': 'எனது சுயவிவரம்',
      'personal_info': 'தனிப்பட்ட தகவல்',
      'full_name': 'முழு பெயர்',
      'phone_number': 'தொலைபேசி எண்',
      'address': 'முகவரி',
      'vehicle_type': 'வாகன வகை',
      'bicycle': 'மிதிவண்டி',
      'bike': 'பைக்',
      'car': 'கார்',
      'save_changes': 'மாற்றங்களைச் சேமிக்கவும்',
      'security': 'பாதுகாப்பு',
      'new_password': 'புதிய கடவுச்சொல்',
      'confirm_new_password': 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'change_password': 'கடவுச்சொல்லை மாற்றவும்',
      'logout_btn': 'வெளியேறு',
      'my_deliveries': 'எனது டெலிவரிகள்',
      'new_requests': 'புதிய கோரிக்கைகள்',
      'accept_delivery': 'டெலிவரியை ஏற்கவும்',
      'pickup': 'பிக்கப்',
      'delivery_label': 'டெலிவரி',
      'inactive_msg':
          'நீங்கள் தற்போது செயலில் இல்லை.\nடெலிவரிகளைப் பெறவும் செயல்திறனைப் பார்க்கவும் கிடைக்கும் தன்மையை (availability) இயக்கவும்.',
      'new_requests_banner': 'உங்களிடம் 2 புதிய டெலிவரி கோரிக்கைகள் உள்ளன!',
      'verified_volunteer': 'சரிபார்க்கப்பட்ட தன்னார்வலர்',
      'top_volunteer': 'சிறந்த தன்னார்வலர்',
      'fifty_deliveries': '50 டெலிவரிகள்',
      'perfect_streak': 'சிறந்த தொடர்ச்சி',
      'hello': 'வணக்கம்',
      'orders_placed': 'ஆர்டர்கள் செய்யப்பட்டன',
      'unable_to_load': 'ஏற்ற முடியவில்லை',
      'your_order_journey': 'உங்கள் ஆர்டர் பயணம்',
      'impact_score': 'தாக்க மதிப்பெண்',
      'impact_score_desc': 'கழிவு குறைப்பில் பங்களிப்பைப் பிரதிபலிக்கிறது.',
      'dietary_preferences': 'உணவு விருப்பங்கள்',
      'select_all': 'அனைத்தையும் தேர்ந்தெடு',
      'clear_all': 'அனைத்தையும் நீக்கு',
      'dietary_prefs_desc':
          'இந்தத் தேர்வுகளின் அடிப்படையில் உங்கள் பீடை வடிகட்டுவோம்.',
      'your_impact': 'உங்கள் தாக்கம்',
      'orders_cancelled': 'ஆர்டர்கள் ரத்து செய்யப்பட்டன',
      'total_spent': 'மொத்த செலவு',
      'detecting_location': 'இருப்பிடத்தைக் கண்டறியும்...',
      'location_unavailable': 'இருப்பிடம் கிடைக்கவில்லை',
      'no_places_found': 'இந்த பிரிவில் இடங்கள் எதுவும் இல்லை',
      'discover_near_you': 'உங்களுக்கு அருகிலுள்ளதைக் கண்டறியவும்',
      'unknown_food': 'அறியப்படாத உணவு',
      'local_seller': 'உள்ளூர் விற்பனையாளர்',
      'FREE': 'இலவசம்',
      'opens': 'திறக்கிறது',
      'ends': 'முடிகிறது',
      'locked': 'பூட்டப்பட்டுள்ளது',
      'expired': 'காலாவதியானது',
      'soon': 'விரைவில்',
      'favorite_restaurants': 'விருப்பமான உணவகங்கள்',
      'no_favorite_restaurants': 'இன்னும் விருப்பமான உணவகங்கள் இல்லை',
      'follow_favorites_desc':
          'உங்களுக்குப் பிடித்த இடங்களை இங்கே காண அவற்றைப் பின்தொடரவும்!',
      'discover_more': 'மேலும் கண்டறியவும்',
      'close': 'மூடு',
      'items': 'பொருட்கள்',
      'no_active_listings': 'தற்போது செயலில் உள்ள பட்டியல்கள் இல்லை',
      'login_with_another_account': 'மற்றொரு கணக்கின் மூலம் உள்நுழைக',
      'my_orders': 'எனது ஆர்டர்கள்',
      'history': 'வரலாறு',
      'no_orders_found': 'ஆர்டர்கள் எதுவும் கிடைக்கவில்லை',
      'quantity': 'அளவு',
      'track_order': 'ஆர்டரைக் கண்காணிக்கவும்',
      'search_in_this_area': 'இந்த பகுதியில் தேடவும்',
      'searching_in_area': 'இந்த பகுதியில் தேடுகிறது...',
      'no_listings_here': 'இங்கே இன்னும் பட்டியல்கள் இல்லை',
      'try_changing_filters':
          'உங்கள் வடிகட்டிகளை மாற்ற அல்லது வேறு பகுதியைத் தேட முயற்சிக்கவும்.',
      'invite_sellers_desc':
          'சமூக வளர்ச்சியை ஊக்குவிக்க இந்த பகுதியில் உள்ள விற்பனையாளர்களை அழைக்கவும்!',
      'search_browse_hint': 'நகரம், உணவு அல்லது வகையைத் தேடுங்கள்...',
      'filter': 'வடிகட்டி',
      'results': 'முடிவுகள்',
      'rating': 'மதிப்பீடு',
      'offers': 'சலுகைகள்',
      'free_food_only': 'இலவச உணவு மட்டும்',
      'apply_filters': 'வடிகட்டிகளைப் பயன்படுத்து',
      'blog': 'வலைப்பதிவு',
      'legal': 'சட்டரீதியானது',
      'account_details': 'கணக்கு விவரங்கள்',
      'notifications': 'அறிவிப்புகள்',
      'change_language': 'மொழியை மாற்றவும்',
      'order_completed': 'ஆர்டர் முடிந்தது',
      'order_cancelled': 'ஆர்டர் ரத்து செய்யப்பட்டது',
      'no_recent_activity': 'சமீபத்திய செயல்பாடு எதுவுமில்லை',
      'just_now': 'இப்போது',
      'days_ago': 'நாட்களுக்கு முன்பு',
      'claim_now': 'இப்போது பெறுங்கள்',
      'reserve': 'முன்பதிவு செய்',
      'availability': 'கிடைக்கும் தன்மை',
      'your_badges': 'உங்கள் பேட்ஜ்கள்',
      'quick_actions': 'விரைவான செயல்கள்',
      'view_orders': 'ஆர்டர்களைப் பார்',
      'error_unsafe_donation':
          'பாதுகாப்பு எச்சரிக்கை: தேர்ந்தெடுக்கப்பட்ட பிக்கப் சாளரம் இந்த வகை உணவிற்கான பாதுகாப்பான நுகர்வு வரம்பை மீறுகிறது।',
      'voice_mode_on':
          'குரல் பயன்முறை செயல்படுத்தப்பட்டது. நான் உங்களுக்கு எப்படி உதவ முடியும்?',
      'online': 'ஆன்லைன்',
      'away': 'வெளியே',
      'your_statistics': 'உங்கள் புள்ளிவிவரங்கள்',
      'last_updated_just_now': 'இப்போது புதுப்பிக்கப்பட்டது',
      'achievements': 'சாதனைகள்',
      'quick_access': 'விரைவான அணுகல்',
      'incoming_requests': 'வரும் கோரிக்கைகள்',
      'verified': 'சரிபார்க்கப்பட்டது',
      'top_star': 'சிறந்த நட்சத்திரம்',
      'social_hero': 'சமூக நாயகன்',
      'new_requests_nearby': 'அருகிலுள்ள புதிய கோரிக்கைகள்',
      'tasks_waiting': 'பணிகள் உங்களுக்காக காத்திருக்கின்றன',
      'accept': 'ஏற்றுக்கொள்',
      'settings': 'அமைப்புகள்',
      'shift_off': 'பணி நேரம் முடிந்தது',
      'failed_to_load_stats': 'புள்ளிவிவரங்களை ஏற்ற முடியவில்லை',
      'retry': 'மீண்டும் முயற்சி செய்',
      'logout': 'வெளியேறு',
      'review_received': 'மதிப்பாய்வு பெறப்பட்டது',
      'mins_ago': 'நிமிடங்களுக்கு முன்பு',
      'hours_ago': 'மணிநேரத்திற்கு முன்பு',
      'yesterday': 'நேற்று',
      'my_listings': 'எனது பட்டியல்கள்',
      'new_listing': 'புதிய பட்டியல்',
      'active': 'செயலில் உள்ளது',
      'completed': 'முடிந்தது',
      'expired_tab': 'காலாவதியானது',
      'relist_listing': 'மீண்டும் பட்டியலிடு',
      'no_listings_yet': 'இன்னும் பட்டியல்கள் இல்லை',
      'no_completed_listings': 'முடிந்த பட்டியல்கள் இல்லை',
      'no_expired_listings': 'காலாவதியான பட்டியல்கள் இல்லை',
      'start_creating_listing_desc':
          'உங்கள் முதல் உணவுப் பட்டியலை உருவாக்குவதன் மூலம் தொடங்கவும்',
      'expires_in': 'காலாவதியாக இன்னும்',
      'expired_ago': 'முன்பு காலாவதியானது',
      'hygiene_status': 'சுகாதார நிலை',
      'edit': 'திருத்து',
      'no_new_requests': 'புதிய கோரிக்கைகள் இல்லை',
      'no_active_deliveries': 'செயலில் உள்ள டெலிவரிகள் இல்லை',
      'no_completed_deliveries': 'முடிந்த டெலிவரிகள் இல்லை',
      'view_details': 'விவரங்களைக் காண்க',
      'placed': 'ஆர்டர் செய்யப்பட்டது',
      'awaiting_volunteer': 'தன்னார்வலருக்காக காத்திருக்கிறது',
      'volunteer_assigned': 'தன்னார்வலர் நியமிக்கப்பட்டார்',
      'assigned': 'நியமிக்கப்பட்டது',
      'picked_up': 'பெறப்பட்டது',
      'in_transit': 'வழியில் உள்ளது',
      'delivered': 'டெலிவரி செய்யப்பட்டது',
      'cancelled': 'ரத்து செய்யப்பட்டது',
      'otp_label': 'ஓடிபி',
      'unknown_item': 'அறியப்படாத பொருள்',
      'order': 'ஆர்டர்',
      'order_details': 'ஆர்டர் விவரங்கள்',
      'cancel_order': 'ஆர்டரை ரத்துசெய்',
      'cancel_confirmation_msg':
          'நிச்சயமாக இந்த ஆர்டரை ரத்துசெய்ய வேண்டுமா? இந்தச் செயலை மாற்ற முடியாது.',
      'keep_it': 'இல்லை, அப்படியே இருக்கட்டும்',
      'yes_cancel': 'ஆம், ரத்துசெய்',
      'order_cancelled_success': 'ஆர்டர் வெற்றிகரமாக ரத்துசெய்யப்பட்டது',
      'failed_to_cancel': 'ரத்துசெய்ய முடியவில்லை',
      'volunteer_delivery': 'தன்னார்வலர் டெலிவரி',
      'self_pickup': 'நேரில் பெறுதல்',
      'fulfillment_mode': 'டெலிவரி முறை',
      'unknown_donor': 'அறியப்படாத கொடையாளர்',
      'chat': 'அட்டை',
      'call': 'அழைப்பு',
      'no_address_provided': 'முகவரி வழங்கப்படவில்லை',
      'pickup_before': 'இதற்கு முன் பெறவும்',
      'handover_otp': 'ஹேண்ட்ஓவர் ஓடிபி',
      'otp_share_warning': 'உணவைப் பெற்றுச் சரிபார்த்த பிறகு மட்டுமே பகிரவும்.',
      'regenerate_otp': 'காலாவதியாகிவிட்டால் மீண்டும் உருவாக்கவும்',
      'finding_volunteer': 'தன்னார்வலரைத் தேடுகிறது...',
      'volunteer_hero': 'தன்னார்வலர் நாயகன்',
      'track_live': 'நேரலை கண்காணிப்பு',
      'order_summary': 'ஆர்டர் சுருக்கம்',
      'delivery_fee': 'டெலிவரி கட்டணம்',
      'platform_fee': 'தளக் கட்டணம்',
      'total': 'மொத்தம்',
      'order_timeline': 'ஆர்டர் காலவரிசை',
      'food_safety_title': 'உணவு பாதுகாப்பு மற்றும் தரம்',
      'food_safety_desc':
          'இந்த பொருள் எங்கள் தன்னார்வலர்களால் தரம் மற்றும் பாதுகாப்பிற்காக ஆய்வு செய்யப்பட்டது.',
      'get_directions': 'வழிமுறைகளைப் பெறுங்கள்',
      'amount': 'தொகை',
      'date': 'தேதி',
      'time': 'நேரம்',
      'order_progress': 'ஆர்டர் முன்னேற்றம்',
      'buyer_info': 'வாங்குபவர் தகவல்',
      'delivery_partner': 'டெலிவரி பார்ட்னர்',
      'pickup_instructions': 'பிக்கப் வழிமுறைகள்',
      'secure_handover': 'பாதுகாப்பான ஹேண்ட்ஓவர்',
      'verify': 'சரிபார்க்கவும்',
      'invalid_otp_msg': 'தயவுசெய்து சரியான 4 இலக்க ஓடிபி உள்ளிடவும்',
      'broadcast_sent': 'ஒளிபரப்பு அனுப்பப்பட்டது...',
      'seller_info': 'விற்பனையாளர் தகவல்',
      'pickup_address': 'பிக்கப் முகவரி',
      'delivery_address': 'டெலிவரி முகவரி',
      'rescue_details': 'மீட்பு விவரங்கள்',
      'report_emergency': 'அவசரநிலையைப் புகாரளி',
      'emergency_desc':
          'நீங்கள் ஏதேனும் சிக்கலை எதிர்கொள்கிறீர்களா? இது வாங்குபவர் மற்றும் விற்பனையாளருக்கு தாமதம் ஏற்படக்கூடும் என்று தெரிவிக்கும்.',
      'report': 'புகாரளி',
      'delivery_verified': 'டெலிவரி சரிபார்க்கப்பட்டது. ஆர்டர் முடிந்தது!',
      'get_help': 'உதவி பெறு',
      'pickup_from': 'இங்கிருந்து பெறவும்',
      'deliver_to': 'இங்கே வழங்கவும்',
      'message': 'செய்தி',
      'cancel_rescue': 'மீட்பை ரத்துசெய்',
      'cancel_rescue_msg':
          'நிச்சயமாக இந்த மீட்பை ரத்துசெய்ய வேண்டுமா? இது ஆர்டரை மீண்டும் பொதுப் பட்டியலுக்கு அனுப்பும்.',
      'rescue_id': 'மீட்பு #',
      'items_count': 'பொருட்கள்',
      'order_failed': 'ஆர்டர் தோல்வியுற்றது',
      'order_cancelled_label': 'ஆர்டர் ரத்து செய்யப்பட்டது',
      'cancelled_by': 'ரத்து செய்தவர்: ',
      'reason_label': 'காரணம்',
      'you_buyer': 'நீங்கள் (வாங்குபவர்)',
      'you_seller': 'நீங்கள் (விற்பனையாளர்)',
      'you_volunteer': 'நீங்கள் (தன்னார்வலர்)',
      'system_label': 'கணினி (System)',
      'system_no_volunteer': 'கணினி (தன்னார்வலர் இல்லை)',
      'km_away': 'கிமீ தொலைவில்',
      'notify_once_assigned': 'ஒதுக்கப்பட்டதும் உங்களுக்கு அறிவிக்கப்படும்.',
      'items_text': 'பொருட்கள்',
      'order_verification_title': 'ஆர்டர் சரிபார்ப்பு',
      'enter_delivery_otp': 'டெலிவரி ஓடிபி உள்ளிடவும்',
      'nav_to_dropoff': 'டெலிவரி இடத்திற்குச் செல்',
      'nav_to_pickup': 'பிக்கப் இடத்திற்குச் செல்',
      'requested': 'கோரப்பட்டது',
      'order_status_updated': 'ஆர்டர் நிலை புதுப்பிக்கப்பட்டது',
      'order_placed_msg': 'ஆர்டர் வெற்றிகரமாக செய்யப்பட்டது!',
      'volunteer_assigned_msg': 'தன்னார்வலர் நியமிக்கப்பட்டு வழியில் உள்ளார்!',
      'picked_up_msg': 'உணவு பெறப்பட்டது! விரைவில் வரும்.',
      'delivered_msg': 'உணவு வழங்கப்பட்டது. மகிழுங்கள்!',
      'completed_msg': 'நீங்கள் உணவை ரசித்தீர்கள் என்று நம்புகிறோம்!',
      'cancelled_msg': 'இந்த ஆர்டர் ரத்து செய்யப்பட்டது.',
      'emergency_hint': 'காரணம் (விபத்து, பைக் பிரச்சனை போன்றவை)',
      'emergency_reported_msg':
          'அவசரநிலை புகாரளிக்கப்பட்டது. உதவி அறிவிக்கப்பட்டது.',
      'rescue_failed': 'மீட்பு தோல்வியுற்றது',
      'rescue_cancelled': 'மீட்பு ரத்து செய்யப்பட்டது',
      'could_not_launch_nav': 'வழிசெலுத்தலைத் தொடங்க முடியவில்லை',
      'pickup_code': 'பிக்கப் குறியீடு',
      'trust_score': 'நம்பகத்தன்மை மதிப்பெண்',
      'earn_trust': 'நம்பிக்கையை பெறுங்கள்',
      'from_backend': 'பின்தளத்திலிருந்து',
      'not_available': 'கிடைக்கவில்லை',
      'from_customers': 'வாடிக்கையாளர்களிடமிருந்து',
      'business_impact': 'வணிக தாக்கம்',
      'meals_shared': 'பகிர்ந்த உணவுகள்',
      'co2_saved': 'சேமிக்கப்பட்ட CO2',
      'total_listings': 'மொத்த பட்டியல்கள்',
      'manage_account': 'கணக்கை நிர்வகி',
      'business_details': 'வணிக விவரங்கள்',
      'accessibility': 'அணுகல்',
      'easy_mode': 'எளிய பயன்முறை',
      'easy_mode_desc': 'பெரிய ஐகான்கள் மற்றும் எளிமையான ஓட்டம்',
      'trust_verification': 'நம்பிக்கை & சரிபார்ப்பு',
      'get_verified': 'சரிபார்க்கவும்',
      'support': 'ஆதரவு',
      'help_with_orders': 'ஆர்டர்களில் உதவி',
      'total_deliveries': 'மொத்த டெலிவரிகள்',
      'details': 'விவரங்கள்',
      'reason_changed_mind': 'மனம் மாறிவிட்டது',
      'reason_accidental': 'தவறுதலாக ஆர்டர் செய்யப்பட்டது',
      'reason_too_far': 'பிக்கப் இடம் மிகத் தொலைவில் உள்ளது',
      'reason_not_responsive': 'விற்பனையாளர் பதிலளிக்கவில்லை',
      'reason_other': 'மற்றவை (கீழே டைப் செய்யவும்)',
      'cannot_cancel_now':
          'பிக்கப்பிற்கு 30 நிமிடங்களுக்கு முன்னதாக ரத்து செய்ய முடியாது',
      'minutes_remaining': 'நிமிடங்கள் மீதமுள்ளன ரத்து செய்ய',
      'enter_reason_hint': 'ரத்து செய்வதற்கான காரணத்தை உள்ளிடவும்...',
    },
    'te': {
      'welcome': 'తిరిగి స్వాగతం',
      'join_us': 'మాతో చేరండి',
      'how_it_works': 'ఇది ఎలా పనిచేస్తుంది',
      'trust': 'నమ్మకం',
      'impact': 'ప్రభావం',
      'login': 'లాగిన్',
      'register': 'కొత్త ఖాతాను సృష్టించు',
      'select_language': 'మీ భాషను ఎంచుకోండి',
      'continue': 'కొనసాగించు',
      'seller_dashboard': 'విక్రేత డాష్‌బోర్డ్',
      'recent_activity': 'ఇటీవలి కార్యాచరణ',
      'welcome_back_user': 'తిరిగి స్వాగతం, ',
      'discover': 'కనుగొనండి',
      'browse': 'బ్రౌజ్ చేయండి',
      'orders': 'ఆర్డర్లు',
      'favourites': 'ఇష్టమైనవి',
      'profile': 'ప్రొఫైల్',
      'home': 'హోమ్',
      'deliveries': 'డెలివరీలు',
      'verification': 'ధృవీకరణ',
      'ratings': 'రేటింగ్‌లు',
      'overview': 'అవలోకనం',
      'listings': 'జాబితాలు',
      'active_listings': 'క్రియాశీల జాబితాలు',
      'pending_orders': 'పెండింగ్ ఆర్డర్లు',
      'avg_rating': 'సగటు రేటింగ్',
      'monthly_earnings': 'నెలవారీ ఆదాయం',
      'new_order_received': 'కొత్త ఆర్డర్ వచ్చింది',
      'listing_expiring_soon': 'జాబితా త్వరలో ముగుస్తుంది',
      'payment_confirmed': 'చెల్లింపు ధృవీకరించబడింది',
      'new_feedback': 'కొత్త అభిప్రాయం',
      'all': 'అన్నీ',
      'free': 'ఉచితం',
      'discounted': 'తగ్గింపు',
      'meals': 'భోజనం',
      'bread_pastries': 'బ్రెడ్ & పేస్ట్రీలు',
      'groceries': 'కిరాణా సరుకులు',
      'pet_food': 'పెంపుడు జంతువుల ఆహారం',
      'vegan': 'వీగన్',
      'vegetarian': 'శాకాహారం',
      'non_vegetarian': 'మాంసాహారం',
      'today': 'నేడు',
      'ends_in': 'ముగిసే సమయం ',
      'my_profile': 'నా ప్రొఫైల్',
      'personal_info': 'వ్యక్తిగత సమాచారం',
      'full_name': 'పూర్తి పేరు',
      'phone_number': 'ఫోన్ నంబర్',
      'address': 'చిరునామా',
      'vehicle_type': 'వాహనం రకం',
      'bicycle': 'సైకిల్',
      'bike': 'బైక్',
      'car': 'కారు',
      'save_changes': 'మార్పులను సేవ్ చేయండి',
      'security': 'భద్రత',
      'new_password': 'కొత్త పాస్‌వర్డ్',
      'confirm_new_password': 'కొత్త పాస్‌వర్డ్ ని ధృవీకరించండి',
      'change_password': 'పాస్‌వర్డ్ మార్చు',
      'logout_btn': 'లాగ్ అవుట్',
      'my_deliveries': 'నా డెలివరీలు',
      'new_requests': 'కొత్త అభ్యర్థనలు',
      'accept_delivery': 'డెలివరీని అంగీకరించు',
      'pickup': 'పికప్',
      'delivery_label': 'డెలివరీ',
      'inactive_msg':
          'మీరు ప్రస్తుతం నిష్క్రియంగా ఉన్నారు.\nడెలివరీలను స్వీకరించడానికి మరియు పనితీరును చూడటానికి అందుబాటును ఆన్ చేయండి.',
      'new_requests_banner': 'మీకు 2 కొత్త డెలివరీ అభ్యర్థనలు వేచి ఉన్నాయి!',
      'verified_volunteer': 'ధృవీకరించబడిన వాలంటీర్',
      'top_volunteer': 'టాప్ వాలంటీర్',
      'fifty_deliveries': '50 డెలివరీలు',
      'perfect_streak': 'పర్ఫెక్ట్ స్ట్రీక్',
      'hello': 'నమస్కారం',
      'orders_placed': 'ఆర్డర్లు చేయబడ్డాయి',
      'unable_to_load': 'లోడ్ చేయడం సాధ్యపడలేదు',
      'your_order_journey': 'మీ ఆర్డర్ ప్రయాణం',
      'impact_score': 'ఇంపాక్ట్ స్కోరు',
      'impact_score_desc': 'వ్యర్థాల తగ్గింపులో మీ సహకారాన్ని తెలియజేస్తుంది.',
      'dietary_preferences': 'ఆహార ప్రాధాన్యతలు',
      'select_all': 'అన్నీ ఎంచుకోండి',
      'clear_all': 'అన్నీ తీసివేయండి',
      'dietary_prefs_desc':
          'ఈ ఎంపికల ఆధారంగా మేము మీ ఫీడ్‌ను ఫిల్టర్ చేస్తాము.',
      'your_impact': 'మీ ప్రభావం',
      'orders_cancelled': 'ఆర్డర్లు రద్దు చేయబడ్డాయి',
      'total_spent': 'మొత్తం ఖర్చు',
      'detecting_location': 'స్థానాన్ని గుర్తిస్తున్నాము...',
      'location_unavailable': 'స్థానం అందుబాటులో లేదు',
      'no_places_found': 'ఈ విభాగంలో ఏ ప్రదేశాలు కనుగొనబడలేదు',
      'discover_near_you': 'మీకు సమీపంలో కనుగొనండి',
      'unknown_food': 'తెలియని ఆహారం',
      'local_seller': 'స్థానిక విక్రేత',
      'FREE': 'ఉచితం',
      'opens': 'ప్రారంభమవుతుంది',
      'ends': 'ముగుస్తుంది',
      'locked': 'లాక్ చేయబడింది',
      'expired': 'గడువు ముగిసింది',
      'soon': 'త్వరలో',
      'favorite_restaurants': 'ఇష్టమైన రెస్టారెంట్లు',
      'no_favorite_restaurants': 'ఇంకా ఇష్టమైన రెస్టారెంట్లు లేవు',
      'follow_favorites_desc':
          'మీకు ఇష్టమైన ప్రదేశాలను ఇక్కడ చూడటానికి వాటిని అనుసరించండి!',
      'discover_more': 'మరిన్ని కనుగొనండి',
      'close': 'మూసివేయి',
      'items': 'వస్తువులు',
      'no_active_listings': 'ప్రస్తుతం యాక్టివ్ లిస్టింగ్లు లేవు',
      'login_with_another_account': 'మరొక ఖాతాతో లాగిన్ చేయండి',
      'my_orders': 'నా ఆర్డర్లు',
      'history': 'చరిత్ర',
      'no_orders_found': 'ఆర్డర్లు కనుగొనబడలేదు',
      'quantity': 'పరిమాణం',
      'track_order': 'ఆర్డర్ ట్రాక్ చేయండి',
      'search_in_this_area': 'ఈ ప్రాంతంలో వెతకండి',
      'searching_in_area': 'ప్రాంతంలో వెతుకుతున్నాము...',
      'no_listings_here': 'ఇక్కడ ఇంకా జాబితాలు లేవు',
      'try_changing_filters':
          'మీ ఫిల్టర్లను మార్చడానికి లేదా మరొక ప్రాంతంలో వెతకడానికి ప్రయత్నించండి.',
      'invite_sellers_desc':
          'కమ్యూనిటీ వృద్ధిని ప్రోత్సహించడానికి ఈ ప్రాంతంలోని విక్రేతలను ఆహ్వానించండి!',
      'search_browse_hint': 'నగరం, ఆహారం లేదా వర్గాన్ని వెతకండి...',
      'filter': 'ఫిల్టర్',
      'results': 'ఫలితాలు',
      'rating': 'రేటింగ్',
      'offers': 'ఆఫర్లు',
      'free_food_only': 'ఉచిత ఆహారం మాత్రమే',
      'apply_filters': 'ఫిల్టర్లను వర్తింపజేయండి',
      'blog': 'బ్లాగ్',
      'legal': 'చట్టపరమైన',
      'account_details': 'ఖాతా వివరాలు',
      'notifications': 'నోటిఫికేషన్లు',
      'change_language': 'భాషను మార్చండి',
      'order_completed': 'ఆర్డర్ పూర్తయింది',
      'order_cancelled': 'ఆర్డర్ రద్దు చేయబడింది',
      'no_recent_activity': 'ఇటీవలి కార్యాచరణ ఏదీ లేదు',
      'just_now': 'ఇప్పుడే',
      'days_ago': 'రోజుల క్రితం',
      'claim_now': 'ఇప్పుడే పొందండి',
      'reserve': 'రిజర్వ్ చేయండి',
      'availability': 'అందుబాటు',
      'your_badges': 'మీ బ్యాడ్జ్‌లు',
      'quick_actions': 'త్వరిత చర్యలు',
      'view_orders': 'ఆర్డర్‌లను చూడండి',
      'error_unsafe_donation':
          'భద్రతా హెచ్చరిక: ఎంచుకున్న పికప్ విండో ఈ రకమైన ఆహారం కోసం సురక్షితమైన వినియోగ పరిమితిని మించిపోయింది।',
      'voice_mode_on':
          'వాయిస్ మోడ్ యాక్టివేట్ చేయబడింది. నేను మీకు ఎలా సహాయం చేయగలను?',
      'online': 'ఆన్‌లైన్',
      'away': 'దూరంగా',
      'your_statistics': 'మీ గణాంకాలు',
      'last_updated_just_now': 'ఇప్పుడే అప్‌డేట్ చేయబడింది',
      'achievements': 'విజయాలు',
      'quick_access': 'త్వరిత ప్రాప్తి',
      'incoming_requests': 'వచ్చే అభ్యర్థనలు',
      'verified': 'ధృవీకరించబడింది',
      'top_star': 'టాప్ స్టార్',
      'social_hero': 'సామాజిక హీరో',
      'new_requests_nearby': 'సమీపంలోని కొత్త అభ్యర్థనలు',
      'tasks_waiting': 'పనులు మీ కోసం వేచి ఉన్నాయి',
      'accept': 'అంగీకరించు',
      'settings': 'సెట్టింగులు',
      'shift_off': 'షిఫ్ట్ ఆఫ్ చేయబడింది',
      'failed_to_load_stats': 'గణాంకాలను లోడ్ చేయడం విఫలమైంది',
      'retry': 'మళ్ళీ ప్రయత్నించండి',
      'logout': 'లాగ్ అవుట్',
      'review_received': 'సమీక్ష స్వీకరించబడింది',
      'mins_ago': 'నిమిషాల క్రితం',
      'hours_ago': 'గంటల క్రితం',
      'yesterday': 'నిన్న',
      'my_listings': 'నా జాబితాలు',
      'new_listing': 'కొత్త జాబితా',
      'active': 'యాక్టివ్',
      'completed': 'పూర్తయింది',
      'expired_tab': 'గడువు ముగిసింది',
      'relist_listing': 'మళ్ళీ లిస్ట్ చేయండి',
      'no_listings_yet': 'ఇంకా జాబితాలు లేవు',
      'no_completed_listings': 'పూర్తయిన జాబితాలు లేవు',
      'no_expired_listings': 'గడువు ముగిసిన జాబితాలు లేవు',
      'start_creating_listing_desc':
          'మీ మొదటి ఆహార జాబితాను సృష్టించడం ద్వారా ప్రారంభించండి',
      'expires_in': 'గడువు ముగియడానికి సమయం',
      'expired_ago': 'క్రితం గడువు ముగిసింది',
      'hygiene_status': 'పరిశుభ్రత స్థితి',
      'edit': 'సవరించు',
      'no_new_requests': 'కొత్త అభ్యర్థనలు లేవు',
      'no_active_deliveries': 'యాక్టివ్ డెలివరీలు లేవు',
      'no_completed_deliveries': 'పూర్తయిన డెలివరీలు లేవు',
      'view_details': 'వివరాలను చూడండి',
      'placed': 'ఆదేశించబడింది',
      'awaiting_volunteer': 'వాలంటీర్ కోసం వేచి ఉంది',
      'volunteer_assigned': 'వాలంటీర్ కేటాయించబడింది',
      'assigned': 'కేటాయించబడింది',
      'picked_up': 'పికప్ చేయబడింది',
      'in_transit': 'మార్గంలో ఉంది',
      'delivered': 'డెలివరీ చేయబడింది',
      'cancelled': 'రద్దు చేయబడింది',
      'otp_label': 'ఓటీపీ',
      'unknown_item': 'తెలియని వస్తువు',
      'order': 'ఆర్డర్',
      'order_details': 'ఆర్డర్ వివరాలు',
      'cancel_order': 'ఆర్డర్ రద్దు చేయండి',
      'cancel_confirmation_msg':
          'మీరు ఖచ్చితంగా ఈ ఆర్డర్‌ను రద్దు చేయాలనుకుంటున్నారా? ఈ చర్యను తిరిగి పొందలేము.',
      'keep_it': 'వద్దు, అలాగే ఉంచండి',
      'yes_cancel': 'అవును, రద్దు చేయండి',
      'order_cancelled_success': 'ఆర్డర్ విజయవంతంగా రద్దు చేయబడింది',
      'failed_to_cancel': 'రద్దు చేయడం విఫలమైంది',
      'volunteer_delivery': 'వాలంటీర్ డెలివరీ',
      'self_pickup': 'నేరుగా తీసుకోవడం',
      'fulfillment_mode': 'పూర్తి మోడ్',
      'unknown_donor': 'తెలియని దాత',
      'chat': 'చాట్',
      'call': 'కాల్',
      'no_address_provided': 'చిరునామా అందించబడలేదు',
      'pickup_before': 'దీనికి ముందు తీసుకోండి',
      'handover_otp': 'హ్యాండోవర్ ఓటీపీ',
      'otp_share_warning':
          'ఆహారం అందుకున్న తర్వాత మరియు తనిఖీ చేసిన తర్వాత మాత్రమే షేర్ చేయండి.',
      'regenerate_otp': 'గడువు ముగిస్తే మళ్ళీ సృష్టించండి',
      'finding_volunteer': 'వాలంటీర్ కోసం వెతుకుతున్నాము...',
      'volunteer_hero': 'వాలంటీర్ హీరో',
      'track_live': 'లైవ్ ట్రాక్ చేయండి',
      'order_summary': 'ఆర్డర్ సారాంశం',
      'delivery_fee': 'డెలివరీ రుసుము',
      'platform_fee': 'ప్లాట్‌ఫాం రుసుము',
      'total': 'మొత్తం',
      'order_timeline': 'ఆర్డర్ కాలక్రమం',
      'food_safety_title': 'ఆహార భద్రత మరియు నాణ్యత',
      'food_safety_desc':
          'మా వాలంటీర్ల ద్వారా ఈ వస్తువు నాణ్యత మరియు భద్రత కోసం తనిఖీ చేయబడింది.',
      'get_directions': 'దిశలు పొందండి',
      'amount': 'మొత్తం',
      'date': 'తేదీ',
      'time': 'సమయం',
      'order_progress': 'ఆర్డర్ పురోగతి',
      'buyer_info': 'కొనుగోలుదారు సమాచారం',
      'delivery_partner': 'డెలివరీ పార్టనర్',
      'pickup_instructions': 'పికప్ సూచనలు',
      'secure_handover': 'సురక్షిత హ్యాండోవర్',
      'verify': 'ధృవీకరించండి',
      'invalid_otp_msg': 'దయచేసి చెల్లుబాటు అయ్యే 4-అంకెల ఓటీపీని నమోదు చేయండి',
      'broadcast_sent': 'బ్రాడ్‌కాస్ట్ పంపబడింది...',
      'seller_info': 'విక్రేత సమాచారం',
      'pickup_address': 'పికప్ చిరునామా',
      'delivery_address': 'డెలివరీ చిరునామా',
      'rescue_details': 'రెస్క్యూ వివరాలు',
      'report_emergency': 'అత్యవసర రిపోర్ట్ చేయండి',
      'emergency_desc':
          'మీరు ఏదైనా సమస్యను ఎదుర్కొంటున్నారా? ఇది కొనుగోలుదారు మరియు విక్రేతకు ఆలస్యం అయ్యే అవకాశం ఉందని తెలియజేస్తుంది.',
      'report': 'రిపోర్ట్',
      'delivery_verified': 'డెలివరీ ధృవీకరించబడింది. ఆర్డర్ పూర్తయింది!',
      'get_help': 'సహాయం పొందండి',
      'pickup_from': 'ఇక్కడి నుండి తీసుకోండి',
      'deliver_to': 'ఇక్కడ డెలివరీ చేయండి',
      'message': 'సందేశం',
      'cancel_rescue': 'రెస్క్యూ రద్దు చేయండి',
      'cancel_rescue_msg':
          'మీరు ఖచ్చితంగా ఈ రెస్క్యూని రద్దు చేయాలనుకుంటున్నారా? ఇది ఆర్డర్‌ను మళ్ళీ పూల్‌కు పంపుతుంది.',
      'rescue_id': 'రెస్క్యూ #',
      'items_count': 'వస్తువులు',
      'order_failed': 'ఆర్డర్ విఫలమైంది',
      'order_cancelled_label': 'ఆర్డర్ రద్దు చేయబడింది',
      'cancelled_by': 'రద్దు చేసిన వారు: ',
      'reason_label': 'కారణం',
      'you_buyer': 'మీరు (కొనుగోలుదారు)',
      'you_seller': 'మీరు (విక్రేత)',
      'you_volunteer': 'మీరు (వాలంటీర్)',
      'system_label': 'సిస్టమ్',
      'system_no_volunteer': 'సిస్టమ్ (వాలంటీర్ అందుబాటులో లేరు)',
      'km_away': 'కిమీ దూరంలో',
      'notify_once_assigned': 'కేటాయించిన తర్వాత మీకు తెలియజేయబడుతుంది.',
      'items_text': 'వస్తువులు',
      'order_verification_title': 'ఆర్డర్ ధృవీకరణ',
      'enter_delivery_otp': 'డెలివరీ ఓటీపీని నమోదు చేయండి',
      'nav_to_dropoff': 'డ్రాప్‌ఆఫ్ ప్రదేశానికి వెళ్ళండి',
      'nav_to_pickup': 'పికప్ ప్రదేశానికి వెళ్ళండి',
      'requested': 'అభ్యర్థించబడింది',
      'order_status_updated': 'ఆర్డర్ స్థితి అప్‌డేట్ చేయబడింది',
      'order_placed_msg': 'ఆర్డర్ విజయవంతంగా చేయబడింది!',
      'volunteer_assigned_msg': 'వాలంటీర్ కేటాయించబడ్డారు & వస్తున్నారు!',
      'picked_up_msg': 'ఆహారం తీసుకోబడింది! త్వరలో వస్తుంది.',
      'delivered_msg': 'ఆహారం డెలివరీ చేయబడింది. ఆనందించండి!',
      'completed_msg': 'మీరు ఆహారాన్ని ఆస్వాదించారని ఆశిస్తున్నాము!',
      'cancelled_msg': 'ఈ ఆర్డర్ రద్దు చేయబడింది.',
      'emergency_hint': 'కారణం (ప్రమాదం, బైక్ సమస్య మొదలైనవి)',
      'emergency_reported_msg':
          'అత్యవసర రిపోర్ట్ చేయబడింది. సహాయం తెలియజేయబడింది.',
      'rescue_failed': 'రెస్క్యూ విఫలమైంది',
      'rescue_cancelled': 'రెస్క్యూ రద్దు చేయబడింది',
      'could_not_launch_nav': 'నావిగేషన్ ప్రారంభించలేకపోయింది',
      'pickup_code': 'పికప్ కోడ్',
      'trust_score': 'నమ్మకం స్కోరు',
      'earn_trust': 'నమ్మకాన్ని సంపాదించండి',
      'from_backend': 'బ్యాకెండ్ నుండి',
      'not_available': 'అందుబాటులో లేదు',
      'from_customers': 'కస్టమర్ల నుండి',
      'business_impact': 'వ్యాపార ప్రభావం',
      'meals_shared': 'పంచిన భోజనాలు',
      'co2_saved': 'ఆదా చేసిన CO2',
      'total_listings': 'మొత్తం జాబితాలు',
      'manage_account': 'ఖాతాను నిర్వహించండి',
      'business_details': 'వ్యాపార వివరాలు',
      'accessibility': 'ప్రాప్యత',
      'easy_mode': 'సరళ మోడ్',
      'easy_mode_desc': 'పెద్ద చిహ్నాలు మరియు సరళమైన వినియోగం',
      'trust_verification': 'నమ్మకం & ధృవీకరణ',
      'get_verified': 'ధృవీకరించుకోండి',
      'support': 'మద్దతు',
      'help_with_orders': 'ఆర్డర్లలో సహాయం',
      'total_deliveries': 'మొత్తం డెలివరీలు',
      'details': 'వివరాలు',
    },
  };

  String translate(String key) {
    // 1. Check static translations first (instant)
    final staticTranslation = _localizedValues[locale.languageCode]?[key];
    if (staticTranslation != null) return staticTranslation;

    // 2. Check dynamic cache (instant if already translated)
    final cachedTranslation = TranslationCache.getTranslation(
      key,
      locale.languageCode,
    );
    if (cachedTranslation != null) return cachedTranslation;

    // 3. Fallback: Trigger dynamic translation (async)
    if (locale.languageCode != 'en') {
      _triggerDynamicTranslation(key);
    }

    return key; // Return the key (e.g., English text) while waiting for translation
  }

  void _triggerDynamicTranslation(String text) async {
    if (locale.languageCode == 'en') return;

    final translation = await TranslationService.translate(
      text,
      locale.languageCode,
    );
    if (translation != null && context != null) {
      // Refresh UI to show the new translation
      final provider = Provider.of<LanguageProvider>(context!, listen: false);
      provider.refreshUI();
    }
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'hi', 'ta', 'te'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  // Added overload to pass context from a custom delegate if needed
  Future<AppLocalizations> loadWithContext(
    Locale locale,
    BuildContext context,
  ) async => AppLocalizations(locale, context);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
