import 'package:flutter/material.dart';
import '../../data/services/backend_service.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome': 'Welcome back',
      'join_us': 'Join Us',
      'how_it_works': 'How it works',
      'trust': 'Trust',
      'impact': 'Impact',
      'login': 'Login',
      'register': 'Create New Account',
      'select_language': 'Select your language',
      'continue': 'Continue',
      'seller_dashboard': 'Seller Dashboard',
      'recent_activity': 'Recent Activity',
      'welcome_back_user': 'Welcome back',
      'discover': 'Discover',
      'browse': 'Browse',
      'orders': 'Orders',
      'favourites': 'Favourites',
      'profile': 'Profile',
      'home': 'Home',
      'deliveries': 'Deliveries',
      'verification': 'Verification',
      'ratings': 'Ratings',
      'overview': 'Overview',
      'listings': 'Listings',
      'active_listings': 'Active Listings',
      'pending_orders': 'Pending Orders',
      'avg_rating': 'Avg. Rating',
      'monthly_earnings': 'Monthly Earnings',
      'new_order_received': 'New Order Received',
      'listing_expiring_soon': 'Listing Expiring Soon',
      'payment_confirmed': 'Payment Confirmed',
      'new_feedback': 'New Feedback',
      'all': 'All',
      'free': 'Free',
      'discounted': 'Discounted',
      'meals': 'Meals',
      'bread_pastries': 'Bread & Pastries',
      'groceries': 'Groceries',
      'pet_food': 'Pet Food',
      'vegan': 'Vegan',
      'vegetarian': 'Vegetarian',
      'non_vegetarian': 'Non-Vegetarian',
      'claim_now': 'Claim Now',
      'reserve': 'Reserve',
      'availability': 'Availability',
      'today': 'Today',
      'your_badges': 'Your Badges',
      'quick_actions': 'Quick Actions',
      'view_orders': 'View Orders',
      'mins_ago': 'mins ago',
      'hours_ago': 'hours ago',
      'yesterday': 'Yesterday',
      'ends_in': 'Ends in ',
      'error_unsafe_donation': 'Safety Warning: The selected pickup window exceeds the safe consumption threshold for this food type.',
      'voice_mode_on': 'Voice mode activated. How can I help?',
      'my_profile': 'My Profile',
      'personal_info': 'Personal Information',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'address': 'Address',
      'vehicle_type': 'Vehicle Type',
      'bicycle': 'Bicycle',
      'bike': 'Bike',
      'car': 'Car',
      'save_changes': 'Save Changes',
      'security': 'Security',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'change_password': 'Change Password',
      'logout_btn': 'Logout',
      'my_deliveries': 'My Deliveries',
      'new_requests': 'New Requests',
      'active': 'Active',
      'completed': 'Completed',
      'view_details': 'View Details',
      'accept_delivery': 'Accept Delivery',
      'pickup': 'Pickup',
      'delivery_label': 'Delivery',
      'inactive_msg': 'You are currently inactive.\nTurn on availability to receive deliveries and view performance.',
      'new_requests_banner': 'You have 2 new delivery requests waiting!',
      'verified_volunteer': 'Verified Volunteer',
      'top_volunteer': 'Top Volunteer',
      'fifty_deliveries': '50 Deliveries',
      'perfect_streak': 'Perfect Streak',
      'hero_pill': 'COMMUNITY-DRIVEN FOOD SHARING',
      'hero_title': 'Small Acts,\nBig Plates.',
      'hero_desc': 'Join a community of food donors and volunteers turning local surplus into neighborhood meals with care and transparency.',
      'how_it_works_title': 'How It Works',
      'give_food': 'Give Food',
      'share_surplus': 'Share surplus food',
      'volunteer_title': 'Volunteer',
      'transport_verify': 'Transport & verify',
      'find_meal': 'Find a meal',
      'discover_local': 'Discover local meals',
      'trust_title': 'Why Trust Us',
      'food_safety': 'Food Safety',
      'rigorous_checks': 'Rigorous safety checks',
      'verified_staff': 'Verified Staff',
      'vetted_partners': 'Vetted volunteers & partners',
      'transparency_title': 'Transparency',
      'track_realtime': 'Track donations in real-time',
      'impact_title': 'Our Global Impact',
      'meals_saved': 'Meals Saved',
      'waste_reduced': 'Waste Reduced',
      'partners': 'Partners',
      'welcome_ahara': 'Welcome back to Ahara',
      'select_role': 'Select your role to login or get started.',
      'login_buyer': 'Login as Buyer',
      'find_meals_nearby': 'Find meals and help nearby',
      'login_seller': 'Login as Seller',
      'share_surplus_seller': 'Share surplus food surplus',
      'login_volunteer': 'Login as Volunteer',
      'help_transport': 'Help transport or verify meals',
      'new_to_ahara': 'New to Ahara? ',
      'create_account': 'Create an Account',
      'no_places_found': 'No places found in this category',
    },
    'hi': {
      'welcome': 'वापस स्वागत है',
      'join_us': 'हमसे जुड़ें',
      'how_it_works': 'यह कैसे काम करता है',
      'trust': 'भरोसा',
      'impact': 'प्रभाव',
      'login': 'लॉगिन',
      'register': 'नया खाता बनाएं',
      'select_language': 'अपनी भाषा चुनें',
      'continue': 'जारी रखें',
      'seller_dashboard': 'विक्रेता डैशबोर्ड',
      'recent_activity': 'हाल की गतिविधि',
      'welcome_back_user': 'वापस स्वागत है, ',
      'discover': 'खोजें',
      'browse': 'ब्राउज़ करें',
      'orders': 'ऑर्डर',
      'favourites': 'पसंदीदा',
      'profile': 'प्रोफ़ाइल',
      'home': 'होम',
      'deliveries': 'डिलिवरी',
      'verification': 'सत्यापन',
      'ratings': 'रेटिंग',
      'overview': 'सिंहावलोकन',
      'listings': 'लिस्टिंग',
      'active_listings': 'सक्रिय लिस्टिंग',
      'pending_orders': 'लंबित ऑर्डर',
      'avg_rating': 'औसत रेटिंग',
      'monthly_earnings': 'मासिक कमाई',
      'new_order_received': 'नया ऑर्डर प्राप्त हुआ',
      'listing_expiring_soon': 'लिस्टिंग जल्द ही समाप्त होने वाली है',
      'payment_confirmed': 'भुगतान की पुष्टि हो गई',
      'new_feedback': 'नई प्रतिक्रिया',
      'all': 'सभी',
      'free': 'मुफ्त',
      'discounted': 'छूट',
      'meals': 'भोजन',
      'bread_pastries': 'ब्रेड और पेस्ट्री',
      'groceries': 'किराना',
      'pet_food': 'पालतू भोजन',
      'vegan': 'शाकाहारी (वीगन)',
      'vegetarian': 'शाकाहारी',
      'non_vegetarian': 'मांसाहारी',
      'claim_now': 'अभी प्राप्त करें',
      'reserve': 'आरक्षित करें',
      'availability': 'उपलब्धता',
      'today': 'आज',
      'your_badges': 'आपके बैज',
      'quick_actions': 'त्वरित कार्य',
      'view_orders': 'ऑर्डर देखें',
      'mins_ago': 'मिनट पहले',
      'hours_ago': 'घंटे पहले',
      'yesterday': 'कल',
      'ends_in': 'समाप्त होगा ',
      'error_unsafe_donation': 'सुरक्षा चेतावनी: चयनित पिकअप विंडो इस प्रकार के भोजन के लिए सुरक्षित उपभोग सीमा से अधिक है।',
      'voice_mode_on': 'वॉयस मोड सक्रिय। मैं आपकी क्या मदद कर सकता हूँ?',
      'my_profile': 'मेरी प्रोफ़ाइल',
      'personal_info': 'व्यक्तिगत जानकारी',
      'full_name': 'पूरा नाम',
      'phone_number': 'फोन नंबर',
      'address': 'पता',
      'vehicle_type': 'वाहन का प्रकार',
      'bicycle': 'साइकिल',
      'bike': 'बाइक',
      'car': 'कार',
      'save_changes': 'बदलाव सहेजें',
      'security': 'सुरक्षा',
      'new_password': 'नया पासवर्ड',
      'confirm_new_password': 'नए पासवर्ड की पुष्टि करें',
      'change_password': 'पासवर्ड बदलें',
      'logout_btn': 'लॉगआउट',
      'my_deliveries': 'मेरी डिलीवरी',
      'new_requests': 'नए अनुरोध',
      'active': 'सक्रिय',
      'completed': 'पूरा हुआ',
      'view_details': 'विवरण देखें',
      'accept_delivery': 'डिलीवरी स्वीकार करें',
      'pickup': 'पिकअप',
      'delivery_label': 'डिलीवरी',
      'inactive_msg': 'आप वर्तमान में निष्क्रिय हैं।\nडिलीवरी प्राप्त करने और प्रदर्शन देखने के लिए उपलब्धता चालू करें।',
      'new_requests_banner': 'आपके पास 2 नए डिलीवरी अनुरोध प्रतीक्षारत हैं!',
      'verified_volunteer': 'सत्यापित स्वयंसेवक',
      'top_volunteer': 'शीर्ष स्वयंसेवक',
      'fifty_deliveries': '50 डिलीवरी',
      'perfect_streak': 'परफेक्ट स्ट्रीక',
      'hero_pill': 'समुदाय-संचालित भोजन साझाकरण',
      'hero_title': 'छोटे कार्य,\nबड़ी थालियाँ।',
      'hero_desc': 'भोजन दाताओं और स्वयंसेवकों के समुदाय में शामिल हों जो स्थानीय अधिशेष को देखभाल और पारदर्शिता के साथ पड़ोस के भोजन में बदलते हैं।',
      'how_it_works_title': 'यह कैसे काम करता है',
      'give_food': 'भोजन दें',
      'share_surplus': 'अतिरिक्त भोजन साझा करें',
      'volunteer_title': 'स्वयंसेवक',
      'transport_verify': 'परिवहन और सत्यापन',
      'find_meal': 'भोजन खोजें',
      'discover_local': 'स्थानीय भोजन खोजें',
      'trust_title': 'हम पर भरोसा क्यों करें',
      'food_safety': 'खाद्य सुरक्षा',
      'rigorous_checks': 'कड़ी सुरक्षा जांच',
      'verified_staff': 'सत्यापित कर्मचारी',
      'vetted_partners': 'जांचे गए स्वयंसेवक और भागीदार',
      'transparency_title': 'पारदर्शिता',
      'track_realtime': 'वास्तविक समय में दान ट्रैक करें',
      'impact_title': 'हमारा वैश्विक प्रभाव',
      'meals_saved': 'भोजन बचाया गया',
      'waste_reduced': 'कचरा कम किया गया',
      'partners': 'भागीदार',
      'welcome_ahara': 'Ahara में फिर से स्वागत है',
      'select_role': 'लॉगिन करने या शुरू करने के लिए अपनी भूमिका चुनें।',
      'login_buyer': 'खरीदार के रूप में लॉगिन करें',
      'find_meals_nearby': 'भोजन खोजें और आस-पास मदद करें',
      'login_seller': 'विक्रेता के रूप में लॉगिन करें',
      'share_surplus_seller': 'अतिरिक्त भोजन साझा करें',
      'login_volunteer': 'स्वयंसेवक के रूप में लॉगिन करें',
      'help_transport': 'परिवहन या भोजन सत्यापित करने में सहायता करें',
      'new_to_ahara': 'Ahara में नए हैं? ',
      'create_account': 'खाता बनाएं',
      'no_places_found': 'इस श्रेणी में कोई स्थान नहीं मिला',
    },
    'ta': {
      'welcome': 'மீண்டும் வருக',
      'join_us': 'எங்களுடன் இணையுங்கள்',
      'how_it_works': 'இது எப்படி வேலை செய்கிறது',
      'trust': 'நம்பிக்கை',
      'impact': 'தாக்கம்',
      'login': 'உள்நுழைக',
      'register': 'புதிய கணக்கை உருவாக்கு',
      'select_language': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
      'continue': 'தொடரவும்',
      'seller_dashboard': 'விற்பனையாளர் டாஷ்போர்டு',
      'recent_activity': 'சமீபத்திய செயல்பாடு',
      'welcome_back_user': 'மீண்டும் வருக, ',
      'discover': 'கண்டுபிடி',
      'browse': 'உலவு',
      'orders': 'ஆர்டர்கள்',
      'favourites': 'விருப்பமானவை',
      'profile': 'சுயவிவரம்',
      'home': 'முகப்பு',
      'deliveries': 'டெலிவரிகள்',
      'verification': 'சரிபார்ப்பு',
      'ratings': 'மதிப்பீடுகள்',
      'overview': 'கண்ணோட்டம்',
      'listings': 'பட்டியல்கள்',
      'active_listings': 'செயலில் உள்ள பட்டியல்கள்',
      'pending_orders': 'நிலுவையில் உள்ள ஆர்டர்கள்',
      'avg_rating': 'சராசரி மதிப்பீடு',
      'monthly_earnings': 'மாதாந்திர வருமானம்',
      'new_order_received': 'புதிய ஆர்டர் பெறப்பட்டது',
      'listing_expiring_soon': 'பட்டியல் விரைவில் காலாவதியாகிறது',
      'payment_confirmed': 'பணம் செலுத்துதல் உறுதி செய்யப்பட்டது',
      'new_feedback': 'புதிய கருத்து',
      'all': 'அனைத்தும்',
      'free': 'இலவசம்',
      'discounted': 'தள்ளுபடி',
      'meals': 'உணவுகள்',
      'bread_pastries': 'ரொட்டி மற்றும் பேஸ்ட்ரிகள்',
      'groceries': 'மளிகைப் பொருட்கள்',
      'pet_food': 'செல்லப்பிராணி உணவு',
      'vegan': 'சைவம் (வீகன்)',
      'vegetarian': 'சைவம்',
      'non_vegetarian': 'அசைவம்',
      'claim_now': 'இப்போது பெறுங்கள்',
      'reserve': 'முன்பதிவு செய்',
      'availability': 'கிடைக்கும் தன்மை',
      'today': 'இன்று',
      'your_badges': 'உங்கள் பேட்ஜ்கள்',
      'quick_actions': 'விரைவான செயல்கள்',
      'view_orders': 'ஆர்டர்களைப் பார்',
      'mins_ago': 'நிமிடங்களுக்கு முன்பு',
      'hours_ago': 'மணிநேரங்களுக்கு முன்பு',
      'yesterday': 'நேற்று',
      'ends_in': 'முடிவடைகிறது ',
      'error_unsafe_donation': 'பாதுகாப்பு எச்சரிக்கை: தேர்ந்தெடுக்கப்பட்ட பிக்கப் சாளரம் இந்த வகை உணவிற்கான பாதுகாப்பான நுகர்வு வரம்பை மீறுகிறது.',
      'voice_mode_on': 'குரல் பயன்முறை செயல்படுத்தப்பட்டது. நான் உங்களுக்கு எப்படி உதவ முடியும்?',
      'my_profile': 'எனது சுயவிவரம்',
      'personal_info': 'தனிப்பட்ட தகவல்',
      'full_name': 'முழு பெயர்',
      'phone_number': 'தொலைபேசி எண்',
      'address': 'முகவரி',
      'vehicle_type': 'வாகன வகை',
      'bicycle': 'மிதிவண்டி',
      'bike': 'பைக்',
      'car': 'கார்',
      'save_changes': 'மாற்றங்களைச் சேமிக்கவும்',
      'security': 'பாதுகாப்பு',
      'new_password': 'புதிய கடவுச்சொல்',
      'confirm_new_password': 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'change_password': 'கடவுச்சொல்லை மாற்றவும்',
      'logout_btn': 'வெளியேறு',
      'my_deliveries': 'எனது டெலிவரிகள்',
      'new_requests': 'புதிய கோரிக்கைகள்',
      'active': 'செயல்பாட்டில் உள்ளது',
      'completed': 'முடிந்தது',
      'view_details': 'விவரங்களைக் காண்க',
      'accept_delivery': 'டெலிவரியை ஏற்கவும்',
      'pickup': 'பிக்கப்',
      'delivery_label': 'டெலிவரி',
      'inactive_msg': 'நீங்கள் தற்போது செயலில் இல்லை.\nடெலிவரிகளைப் பெறவும் செயல்திறனைப் பார்க்கவும் கிடைக்கும் தன்மையை (availability) இயக்கவும்.',
      'new_requests_banner': 'உங்களிடம் 2 புதிய டெலிவரி கோரிக்கைகள் உள்ளன!',
      'verified_volunteer': 'சரிபார்க்கப்பட்ட தன்னார்வலர்',
      'top_volunteer': 'சிறந்த தன்னார்வலர்',
      'fifty_deliveries': '50 டெலிவரிகள்',
      'perfect_streak': 'சரியான தொடர்ச்சி',
      'hero_pill': 'சமூகத்தால் நடத்தப்படும் உணவு பகிர்வு',
      'hero_title': 'சிறிய செயல்கள்,\nபெரிய தட்டுகள்.',
      'hero_desc': 'கவனிப்பு மற்றும் வெளிப்படைத்தன்மையுடன் உள்ளூர் உபரியை அருகிலுள்ள உணவாக மாற்றும் உணவு நன்கொடையாளர்கள் மற்றும் தன்னார்வலர்களின் சமூகத்தில் சேரவும்.',
      'how_it_works_title': 'இது எப்படி வேலை செய்கிறது',
      'give_food': 'உணவு கொடுங்கள்',
      'share_surplus': 'உபரி உணவை பகிரவும்',
      'volunteer_title': 'தன்னார்வலர்',
      'transport_verify': 'போக்குவரத்து & சரிபார்த்தல்',
      'find_meal': 'உணவைக் கண்டறியவும்',
      'discover_local': 'உள்ளூர் உணவுகளை கண்டறியவும்',
      'trust_title': 'எங்களை ஏன் நம்ப வேண்டும்',
      'food_safety': 'உணவு பாதுகாப்பு',
      'rigorous_checks': 'கடுமையான பாதுகாப்பு சோதனைகள்',
      'verified_staff': 'சரிபார்க்கப்பட்ட ஊழியர்கள்',
      'vetted_partners': 'பரிசோதிக்கப்பட்ட தன்னார்வலர்கள் & கூட்டாளர்கள்',
      'transparency_title': 'வெளிப்படைத்தன்மை',
      'track_realtime': 'நன்கொடைகளை நிகழ்நேரத்தில் கண்காணிக்கவும்',
      'impact_title': 'எங்கள் உலகளாவிய தாக்கம்',
      'meals_saved': 'காப்பற்றப்பட்ட உணவுகள்',
      'waste_reduced': 'கழிவுகள் குறைக்கப்பட்டது',
      'partners': 'கூட்டாளர்கள்',
      'welcome_ahara': 'Ahara-விற்கு மீண்டும் வரவேற்கிறோம்',
      'select_role': 'உள்நுழைய அல்லது தொடங்க உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்.',
      'login_buyer': 'வாங்குபவராக உள்நுழைக',
      'find_meals_nearby': 'உணவுகளைக் கண்டறிந்து அருகில் உதவுங்கள்',
      'login_seller': 'விற்பனையாளராக உள்நுழைக',
      'share_surplus_seller': 'உபரி உணவை பகிரவும்',
      'login_volunteer': 'தன்னார்வலராக உள்நுழைக',
      'help_transport': 'போக்குவரத்து அல்லது உணவை சரிபார்க்க உதவுங்கள்',
      'new_to_ahara': 'Ahara-விற்குப் புதியவரா? ',
      'create_account': 'கணக்கை உருவாக்கவும்',
      'no_places_found': 'இந்த பிரிவில் எந்த இடங்களும் காணப்படவில்லை',
    },
    'te': {
      'welcome': 'తిరిగి స్వాగతం',
      'join_us': 'మాతో చేరండి',
      'how_it_works': 'ఇది ఎలా పనిచేస్తుంది',
      'trust': 'నమ్మకం',
      'impact': 'ప్రభావం',
      'login': 'లాగిన్',
      'register': 'కొత్త ఖాతాను సృష్టించు',
      'select_language': 'మీ భాషను ఎంచుకోండి',
      'continue': 'కొనసాగించు',
      'seller_dashboard': 'విక్రేత డాష్‌బోర్డ్',
      'recent_activity': 'ఇటీవలి కార్యాచరణ',
      'welcome_back_user': 'తిరిగి స్వాగతం, ',
      'discover': 'కనుగొనండి',
      'browse': 'బ్రౌజ్ చేయండి',
      'orders': 'ఆర్డర్లు',
      'favourites': 'ఇష్టమైనవి',
      'profile': 'ప్రొఫైల్',
      'home': 'హోమ్',
      'deliveries': 'డెలివరీలు',
      'verification': 'ధృవీకరణ',
      'ratings': 'రేటింగ్‌లు',
      'overview': 'అవలోకనం',
      'listings': 'జాబితాలు',
      'active_listings': 'క్రియాశీల జాబితాలు',
      'pending_orders': 'పెండింగ్ ఆర్డర్లు',
      'avg_rating': 'సగటు రేటింగ్',
      'monthly_earnings': 'నెలవారీ ఆదాయం',
      'new_order_received': 'కొత్త ఆర్డర్ వచ్చింది',
      'listing_expiring_soon': 'జాబితా త్వరలో ముగుస్తుంది',
      'payment_confirmed': 'చెల్లింపు ధృవీకరించబడింది',
      'new_feedback': 'కొత్త అభిప్రాయం',
      'all': 'అన్నీ',
      'free': 'ఉచితం',
      'discounted': 'తగ్గింపు',
      'meals': 'భోజనం',
      'bread_pastries': 'బ్రెడ్ & పేస్ట్రీలు',
      'groceries': 'కిరాణా సరుకులు',
      'pet_food': 'పెంపుడు జంతువుల ఆహారం',
      'vegan': 'వీగన్',
      'vegetarian': 'శాకాహారం',
      'non_vegetarian': 'మాంసాహారం',
      'claim_now': 'ఇప్పుడే పొందండి',
      'reserve': 'రిజర్వ్ చేయండి',
      'availability': 'అందుబాటు',
      'today': 'నేడు',
      'your_badges': 'మీ బ్యాడ్జ్‌లు',
      'quick_actions': 'త్వరిత చర్యలు',
      'view_orders': 'ఆర్డర్‌లను చూడండి',
      'mins_ago': 'నిమిషాల క్రితం',
      'hours_ago': 'గంటల క్రితం',
      'yesterday': 'నిన్న',
      'ends_in': 'ముగిసే సమయం ',
      'error_unsafe_donation': 'భద్రతా హెచ్చరిక: ఎంచుకున్న పికప్ విండో ఈ రకమైన ఆహారం కోసం సురక్షితమైన వినియోగ పరిమితిని మించిపోయింది.',
      'voice_mode_on': 'వాయిస్ మోడ్ యాక్టివేట్ చేయబడింది. నేను మీకు ఎలా సహాయం చేయగలను?',
      'my_profile': 'నా ప్రొఫైల్',
      'personal_info': 'వ్యక్తిగత సమాచారం',
      'full_name': 'పూర్తి పేరు',
      'phone_number': 'ఫోన్ నంబర్',
      'address': 'చిరునామా',
      'vehicle_type': 'వాహనం రకం',
      'bicycle': 'సైకిల్',
      'bike': 'బైక్',
      'car': 'కారు',
      'save_changes': 'మార్పులను సేవ్ చేయండి',
      'security': 'భద్రత',
      'new_password': 'కొత్త పాస్‌వర్డ్',
      'confirm_new_password': 'కొత్త పాస్‌వర్డ్ ని ధృవీకరించండి',
      'change_password': 'పాస్‌వర్డ్ మార్చు',
      'logout_btn': 'లాగ్ అవుట్',
      'my_deliveries': 'నా డెలివరీలు',
      'new_requests': 'కొత్త అభ్యర్థనలు',
      'active': 'యాక్టివ్',
      'completed': 'పూర్తయింది',
      'view_details': 'వివరాలను చూడండి',
      'accept_delivery': 'డెలివరీని అంగీకరించు',
      'pickup': 'పికప్',
      'delivery_label': 'డెలివరీ',
      'inactive_msg': 'మీరు ప్రస్తుతం నిష్క్రియంగా ఉన్నారు.\nడెలివరీలను స్వీకరించడానికి మరియు పనితీరును చూడటానికి అందుబాటును ఆన్ చేయండి.',
      'new_requests_banner': 'మీకు 2 కొత్త డెలివరీ అభ్యర్థనలు వేచి ఉన్నాయి!',
      'verified_volunteer': 'ధృవీకరించబడిన వాలంటీర్',
      'top_volunteer': 'టాప్ వాలంటీర్',
      'fifty_deliveries': '50 డెలివరీలు',
      'perfect_streak': 'పర్ఫెక్ట్ స్ట్రీక్',
      'hero_pill': 'సంఘం-ఆధారిత ఆహార భాగస్వామ్యం',
      'hero_title': 'చిన్న పనులు,\nపెద్ద కంచాలు.',
      'hero_desc': 'స్థానిక మిగులు ఆహారాన్ని శ్రద్ధ మరియు పారదర్శకతతో ఇరుగుపొరుగున భోజనంగా మార్చే ఆహార దాతలు మరియు వాలంటీర్ల సంఘంలో చేరండి.',
      'how_it_works_title': 'ఇది ఎలా పనిచేస్తుంది',
      'give_food': 'ఆహారం ఇవ్వండి',
      'share_surplus': 'మిగులు ఆహారాన్ని పంచుకోండి',
      'volunteer_title': 'వాలంటీర్',
      'transport_verify': 'రవాణా & ధృవీకరణ',
      'find_meal': 'భోజనాన్ని కనుగొనండి',
      'discover_local': 'స్థానిక భోజనాలను కనుగొనండి',
      'trust_title': 'మమ్మల్ని ఎందుకు నమ్మాలి',
      'food_safety': 'ఆహార భద్రత',
      'rigorous_checks': 'కఠినమైన భద్రతా తనిఖీలు',
      'verified_staff': 'ధృవీకరించబడిన సిబ్బంది',
      'vetted_partners': 'తనిఖీ చేయబడిన వాలంటీర్లు & భాగస్వాములు',
      'transparency_title': 'పారదర్శకత',
      'track_realtime': 'విరాళాలను నిజ సమయంలో ట్రాక్ చేయండి',
      'impact_title': 'మా ప్రపంచ ప్రభావం',
      'meals_saved': 'సేవ్ చేయబడిన భోజనాలు',
      'waste_reduced': 'తగ్గించబడిన వ్యర్థాలు',
      'partners': 'భాగస్వాములు',
      'welcome_ahara': 'Ahara కి తిరిగి స్వాగతం',
      'select_role': 'లాగిన్ చేయడానికి లేదా ప్రారంభించడానికి మీ పాత్రను ఎంచుకోండి.',
      'login_buyer': 'కొనుగోలుదారుగా లాగిన్ చేయండి',
      'find_meals_nearby': 'సమీపంలోని భోజనాన్ని కనుగొని, సహాయం చేయండి',
      'login_seller': 'విక్రేతగా లాగిన్ చేయండి',
      'share_surplus_seller': 'మిగులు ఆహారాన్ని పంచుకోండి',
      'login_volunteer': 'వాలంటీర్‌గా లాగిన్ చేయండి',
      'help_transport': 'రవాణా లేదా భోజనాన్ని ధృవీకరించడంలో సహాయపడండి',
      'new_to_ahara': 'Ahara కి కొత్తా? ',
      'create_account': 'ఖాతాను సృష్టించండి',
      'no_places_found': 'ఈ వర్గంలో ఎలాంటి స్థలాలు కనుగొనబడలేదు',
    },
  };

  static VoidCallback? onDynamicTranslationUpdated;
  
  static final Map<String, Map<String, String>> _dynamicCache = {
    'hi': {}, 'ta': {}, 'te': {}, 'en': {}
  };

  String translate(String key) {
    if (locale.languageCode == 'en') return _localizedValues['en']?[key] ?? key;
    
    // 1. Check static translations first
    if (_localizedValues[locale.languageCode]!.containsKey(key)) {
      return _localizedValues[locale.languageCode]![key]!;
    }
    
    // 2. Identify default English text (or key if not found in English static map)
    final defaultText = _localizedValues['en']?[key] ?? key;
    
    // 3. Check dynamic cache
    if (_dynamicCache[locale.languageCode]!.containsKey(defaultText)) {
      return _dynamicCache[locale.languageCode]![defaultText]!;
    }
    
    // 4. Kick off async translation for missing strings
    _fetchDynamicTranslation(defaultText, locale.languageCode);
    
    // Return English text/key while fetching translation in background
    return defaultText;
  }
  
  static void _fetchDynamicTranslation(String text, String langCode) async {
    // Save placeholder to prevent duplicate API requests for the same string
    if (_dynamicCache[langCode]!.containsKey(text)) return;
    _dynamicCache[langCode]![text] = text; 
    
    final translated = await BackendService.translateText(text, langCode);
    if (translated != null && translated.isNotEmpty && translated != text) {
      _dynamicCache[langCode]![text] = translated;
      // Notify listeners (LanguageProvider) to rebuild the UI with translated text
      onDynamicTranslationUpdated?.call();
    }
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'hi', 'ta', 'te'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
